# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageipapdriver.ui'
#
# Created: Mon Mar  2 21:04:05 2015
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PageiPapDriver(object):
    def setupUi(self, PageiPapDriver):
        PageiPapDriver.setObjectName("PageiPapDriver")
        PageiPapDriver.resize(800, 613)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PageiPapDriver.sizePolicy().hasHeightForWidth())
        PageiPapDriver.setSizePolicy(sizePolicy)
        PageiPapDriver.setMinimumSize(QtCore.QSize(800, 613))
        self.gridlayout = QtGui.QGridLayout(PageiPapDriver)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.frame_description = QtGui.QFrame(PageiPapDriver)
        self.frame_description.setMinimumSize(QtCore.QSize(16, 50))
        self.frame_description.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frame_description.setAutoFillBackground(True)
        self.frame_description.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_description.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_description.setObjectName("frame_description")
        self.hboxlayout = QtGui.QHBoxLayout(self.frame_description)
        self.hboxlayout.setObjectName("hboxlayout")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_2 = QtGui.QLabel(self.frame_description)
        self.label_2.setMaximumSize(QtCore.QSize(31, 26))
        self.label_2.setObjectName("label_2")
        self.hboxlayout1.addWidget(self.label_2)
        self.dscDriverName = QtGui.QLabel(self.frame_description)
        self.dscDriverName.setMaximumSize(QtCore.QSize(16777215, 26))
        self.dscDriverName.setObjectName("dscDriverName")
        self.hboxlayout1.addWidget(self.dscDriverName)
        self.hboxlayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_4 = QtGui.QLabel(self.frame_description)
        self.label_4.setMaximumSize(QtCore.QSize(41, 26))
        self.label_4.setObjectName("label_4")
        self.hboxlayout2.addWidget(self.label_4)
        self.dscActive = QtGui.QLabel(self.frame_description)
        self.dscActive.setObjectName("dscActive")
        self.hboxlayout2.addWidget(self.dscActive)
        self.hboxlayout.addLayout(self.hboxlayout2)
        self.btnBlink = QtGui.QPushButton(self.frame_description)
        self.btnBlink.setCheckable(True)
        self.btnBlink.setObjectName("btnBlink")
        self.hboxlayout.addWidget(self.btnBlink)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_3 = QtGui.QLabel(self.frame_description)
        self.label_3.setMaximumSize(QtCore.QSize(63, 26))
        self.label_3.setObjectName("label_3")
        self.hboxlayout3.addWidget(self.label_3)
        self.dscSignature = QtGui.QLabel(self.frame_description)
        self.dscSignature.setObjectName("dscSignature")
        self.hboxlayout3.addWidget(self.dscSignature)
        self.hboxlayout.addLayout(self.hboxlayout3)
        self.gridlayout.addWidget(self.frame_description, 0, 0, 1, 1)
        self.frame_right = QtGui.QFrame(PageiPapDriver)
        self.frame_right.setMinimumSize(QtCore.QSize(220, 499))
        self.frame_right.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_right.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.vboxlayout = QtGui.QVBoxLayout(self.frame_right)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtGui.QLabel(self.frame_right)
        self.label.setPixmap(QtGui.QPixmap(":/logos/IcepapCfg Icons/Icepap.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.stackedWidget = QtGui.QStackedWidget(self.frame_right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(220, 353))
        self.stackedWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageTest = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTest.sizePolicy().hasHeightForWidth())
        self.pageTest.setSizePolicy(sizePolicy)
        self.pageTest.setMinimumSize(QtCore.QSize(220, 0))
        self.pageTest.setMaximumSize(QtCore.QSize(220, 16777215))
        self.pageTest.setObjectName("pageTest")
        self.gridlayout1 = QtGui.QGridLayout(self.pageTest)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(2)
        self.gridlayout1.setObjectName("gridlayout1")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem, 1, 0, 1, 1)
        self.frame_test = QtGui.QFrame(self.pageTest)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_test.sizePolicy().hasHeightForWidth())
        self.frame_test.setSizePolicy(sizePolicy)
        self.frame_test.setMinimumSize(QtCore.QSize(220, 300))
        self.frame_test.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_test.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_test.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_test.setObjectName("frame_test")
        self.gridlayout2 = QtGui.QGridLayout(self.frame_test)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.btnGO = QtGui.QPushButton(self.frame_test)
        self.btnGO.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/small_icons/IcepapCFG Icons Petits/go-absolute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGO.setIcon(icon)
        self.btnGO.setIconSize(QtCore.QSize(22, 22))
        self.btnGO.setObjectName("btnGO")
        self.gridlayout2.addWidget(self.btnGO, 5, 4, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_test)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.frame_4)
        self.hboxlayout4.setSpacing(0)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName("hboxlayout4")
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem1)
        self.frame_leds = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_leds.sizePolicy().hasHeightForWidth())
        self.frame_leds.setSizePolicy(sizePolicy)
        self.frame_leds.setMinimumSize(QtCore.QSize(171, 48))
        self.frame_leds.setMaximumSize(QtCore.QSize(171, 48))
        self.frame_leds.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_leds.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_leds.setObjectName("frame_leds")
        self.textLabel1_6_4 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_4.setGeometry(QtCore.QRect(40, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_4.setFont(font)
        self.textLabel1_6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_4.setObjectName("textLabel1_6_4")
        self.LedLimitPos = Led(self.frame_leds)
        self.LedLimitPos.setGeometry(QtCore.QRect(137, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedLimitPos.sizePolicy().hasHeightForWidth())
        self.LedLimitPos.setSizePolicy(sizePolicy)
        self.LedLimitPos.setMinimumSize(QtCore.QSize(24, 24))
        self.LedLimitPos.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedLimitPos.setPalette(palette)
        self.LedLimitPos.setObjectName("LedLimitPos")
        self.textLabel1_6_5 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_5.setGeometry(QtCore.QRect(8, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_5.setFont(font)
        self.textLabel1_6_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textLabel1_6_5.setObjectName("textLabel1_6_5")
        self.LedHome = Led(self.frame_leds)
        self.LedHome.setGeometry(QtCore.QRect(72, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedHome.sizePolicy().hasHeightForWidth())
        self.LedHome.setSizePolicy(sizePolicy)
        self.LedHome.setMinimumSize(QtCore.QSize(24, 24))
        self.LedHome.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedHome.setPalette(palette)
        self.LedHome.setObjectName("LedHome")
        self.textLabel1_6_3 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_3.setGeometry(QtCore.QRect(72, 35, 25, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_3.setFont(font)
        self.textLabel1_6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_3.setObjectName("textLabel1_6_3")
        self.textLabel1_6 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6.setGeometry(QtCore.QRect(137, 35, 25, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6.setFont(font)
        self.textLabel1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6.setObjectName("textLabel1_6")
        self.LedStep = Led(self.frame_leds)
        self.LedStep.setGeometry(QtCore.QRect(40, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedStep.sizePolicy().hasHeightForWidth())
        self.LedStep.setSizePolicy(sizePolicy)
        self.LedStep.setMinimumSize(QtCore.QSize(24, 24))
        self.LedStep.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedStep.setPalette(palette)
        self.LedStep.setObjectName("LedStep")
        self.LedError = Led(self.frame_leds)
        self.LedError.setGeometry(QtCore.QRect(8, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedError.sizePolicy().hasHeightForWidth())
        self.LedError.setSizePolicy(sizePolicy)
        self.LedError.setMinimumSize(QtCore.QSize(24, 24))
        self.LedError.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedError.setPalette(palette)
        self.LedError.setObjectName("LedError")
        self.LedLimitNeg = Led(self.frame_leds)
        self.LedLimitNeg.setGeometry(QtCore.QRect(105, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedLimitNeg.sizePolicy().hasHeightForWidth())
        self.LedLimitNeg.setSizePolicy(sizePolicy)
        self.LedLimitNeg.setMinimumSize(QtCore.QSize(24, 24))
        self.LedLimitNeg.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedLimitNeg.setPalette(palette)
        self.LedLimitNeg.setObjectName("LedLimitNeg")
        self.textLabel1_6_2 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_2.setGeometry(QtCore.QRect(105, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_2.setFont(font)
        self.textLabel1_6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_2.setObjectName("textLabel1_6_2")
        self.hboxlayout4.addWidget(self.frame_leds)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem2)
        self.gridlayout2.addWidget(self.frame_4, 3, 0, 1, 5)
        self.textLabel1_3_3_2 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3_3_2.setFont(font)
        self.textLabel1_3_3_2.setObjectName("textLabel1_3_3_2")
        self.gridlayout2.addWidget(self.textLabel1_3_3_2, 1, 0, 1, 3)
        self.txtAcceleration = QtGui.QLineEdit(self.frame_test)
        self.txtAcceleration.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtAcceleration.setFont(font)
        self.txtAcceleration.setObjectName("txtAcceleration")
        self.gridlayout2.addWidget(self.txtAcceleration, 1, 3, 1, 2)
        self.textLabel3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3.setFont(font)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout2.addWidget(self.textLabel3, 4, 0, 1, 1)
        self.btnStopMotor = QtGui.QPushButton(self.frame_test)
        self.btnStopMotor.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/IcepapCfg Icons/gnome-session-halt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStopMotor.setIcon(icon1)
        self.btnStopMotor.setIconSize(QtCore.QSize(22, 22))
        self.btnStopMotor.setObjectName("btnStopMotor")
        self.gridlayout2.addWidget(self.btnStopMotor, 6, 1, 1, 1)
        self.txtMvAbsolute = QtGui.QLineEdit(self.frame_test)
        self.txtMvAbsolute.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtMvAbsolute.setFont(font)
        self.txtMvAbsolute.setObjectName("txtMvAbsolute")
        self.gridlayout2.addWidget(self.txtMvAbsolute, 5, 3, 1, 1)
        self.textLabel1_3_3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3_3.setFont(font)
        self.textLabel1_3_3.setObjectName("textLabel1_3_3")
        self.gridlayout2.addWidget(self.textLabel1_3_3, 0, 0, 1, 3)
        self.frame = QtGui.QFrame(self.frame_test)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridlayout2.addWidget(self.frame, 2, 0, 1, 5)
        self.LCDPosition = QtGui.QLCDNumber(self.frame_test)
        self.LCDPosition.setMinimumSize(QtCore.QSize(0, 24))
        self.LCDPosition.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 59, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 68, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 59, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 68, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDPosition.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDPosition.setFont(font)
        self.LCDPosition.setAutoFillBackground(True)
        self.LCDPosition.setFrameShape(QtGui.QFrame.Panel)
        self.LCDPosition.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDPosition.setNumDigits(9)
        self.LCDPosition.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDPosition.setObjectName("LCDPosition")
        self.gridlayout2.addWidget(self.LCDPosition, 4, 1, 1, 4)
        self.txtSpeed = QtGui.QLineEdit(self.frame_test)
        self.txtSpeed.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.txtSpeed.setFont(font)
        self.txtSpeed.setObjectName("txtSpeed")
        self.gridlayout2.addWidget(self.txtSpeed, 0, 3, 1, 2)
        self.btnEnable = QtGui.QPushButton(self.frame_test)
        self.btnEnable.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.btnEnable.setFont(font)
        self.btnEnable.setCheckable(True)
        self.btnEnable.setChecked(False)
        self.btnEnable.setObjectName("btnEnable")
        self.gridlayout2.addWidget(self.btnEnable, 6, 0, 1, 1)
        self.btnGORelativePos = QtGui.QPushButton(self.frame_test)
        self.btnGORelativePos.setMaximumSize(QtCore.QSize(24, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/small_icons/IcepapCFG Icons Petits/go-relative.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGORelativePos.setIcon(icon2)
        self.btnGORelativePos.setIconSize(QtCore.QSize(22, 22))
        self.btnGORelativePos.setObjectName("btnGORelativePos")
        self.gridlayout2.addWidget(self.btnGORelativePos, 6, 4, 1, 1)
        self.btnGORelativeNeg = QtGui.QPushButton(self.frame_test)
        self.btnGORelativeNeg.setMaximumSize(QtCore.QSize(24, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/small_icons/IcepapCFG Icons Petits/go-relative2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGORelativeNeg.setIcon(icon3)
        self.btnGORelativeNeg.setIconSize(QtCore.QSize(22, 22))
        self.btnGORelativeNeg.setObjectName("btnGORelativeNeg")
        self.gridlayout2.addWidget(self.btnGORelativeNeg, 6, 2, 1, 1)
        self.textLabel1_3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3.setFont(font)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.gridlayout2.addWidget(self.textLabel1_3, 5, 0, 1, 3)
        self.txtGORelative = QtGui.QLineEdit(self.frame_test)
        self.txtGORelative.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtGORelative.setFont(font)
        self.txtGORelative.setObjectName("txtGORelative")
        self.gridlayout2.addWidget(self.txtGORelative, 6, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame_test)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout5.setSpacing(2)
        self.hboxlayout5.setMargin(2)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.sliderJog = QtGui.QSlider(self.groupBox)
        self.sliderJog.setMouseTracking(False)
        self.sliderJog.setMinimum(-4)
        self.sliderJog.setMaximum(4)
        self.sliderJog.setPageStep(1)
        self.sliderJog.setProperty("value", QtCore.QVariant(0))
        self.sliderJog.setSliderPosition(0)
        self.sliderJog.setOrientation(QtCore.Qt.Horizontal)
        self.sliderJog.setInvertedAppearance(False)
        self.sliderJog.setInvertedControls(False)
        self.sliderJog.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderJog.setTickInterval(2)
        self.sliderJog.setObjectName("sliderJog")
        self.hboxlayout5.addWidget(self.sliderJog)
        self.gridlayout2.addWidget(self.groupBox, 7, 0, 1, 5)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.cmdCSWITCH = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.cmdCSWITCH.sizePolicy().hasHeightForWidth())
        self.cmdCSWITCH.setSizePolicy(sizePolicy)
        self.cmdCSWITCH.setObjectName("cmdCSWITCH")
        self.cmdCSWITCH.addItem(QtCore.QString())
        self.cmdCSWITCH.addItem(QtCore.QString())
        self.cmdCSWITCH.addItem(QtCore.QString())
        self.horizontalLayout_2.addWidget(self.cmdCSWITCH)
        self.gridlayout2.addWidget(self.groupBox_2, 8, 0, 1, 5)
        self.gridlayout1.addWidget(self.frame_test, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTest)
        self.pageHistoric = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageHistoric.sizePolicy().hasHeightForWidth())
        self.pageHistoric.setSizePolicy(sizePolicy)
        self.pageHistoric.setMinimumSize(QtCore.QSize(220, 0))
        self.pageHistoric.setMaximumSize(QtCore.QSize(220, 420))
        self.pageHistoric.setObjectName("pageHistoric")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.pageHistoric)
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.historicWidget = HistoricCfgWidget(self.pageHistoric)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historicWidget.sizePolicy().hasHeightForWidth())
        self.historicWidget.setSizePolicy(sizePolicy)
        self.historicWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.historicWidget.setMaximumSize(QtCore.QSize(220, 420))
        self.historicWidget.setObjectName("historicWidget")
        self.hboxlayout6.addWidget(self.historicWidget)
        self.stackedWidget.addWidget(self.pageHistoric)
        self.vboxlayout.addWidget(self.stackedWidget)
        self.btnSendCfg = QtGui.QPushButton(self.frame_right)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/small_icons/IcepapCfg Icons/Icepapicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSendCfg.setIcon(icon4)
        self.btnSendCfg.setIconSize(QtCore.QSize(20, 20))
        self.btnSendCfg.setObjectName("btnSendCfg")
        self.vboxlayout.addWidget(self.btnSendCfg)
        self.btnSaveCfg = QtGui.QPushButton(self.frame_right)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/IcepapCfg Icons/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveCfg.setIcon(icon5)
        self.btnSaveCfg.setIconSize(QtCore.QSize(20, 20))
        self.btnSaveCfg.setObjectName("btnSaveCfg")
        self.vboxlayout.addWidget(self.btnSaveCfg)
        self.btnUndo = QtGui.QPushButton(self.frame_right)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/small_icons/IcepapCFG Icons Petits/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUndo.setIcon(icon6)
        self.btnUndo.setIconSize(QtCore.QSize(20, 20))
        self.btnUndo.setObjectName("btnUndo")
        self.vboxlayout.addWidget(self.btnUndo)
        self.btnRestore = QtGui.QPushButton(self.frame_right)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/IcepapCfg Icons/update-manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRestore.setIcon(icon7)
        self.btnRestore.setIconSize(QtCore.QSize(20, 20))
        self.btnRestore.setObjectName("btnRestore")
        self.vboxlayout.addWidget(self.btnRestore)
        self.gridlayout.addWidget(self.frame_right, 0, 1, 2, 1)
        self.tabWidget = QtGui.QTabWidget(PageiPapDriver)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_TuneAndTesting = QtGui.QWidget()
        self.tab_TuneAndTesting.setObjectName("tab_TuneAndTesting")
        self.gridlayout3 = QtGui.QGridLayout(self.tab_TuneAndTesting)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem3, 2, 2, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout.setObjectName("gridLayout")
        self.label_55 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_55.setFont(font)
        self.label_55.setTextFormat(QtCore.Qt.PlainText)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 0, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_13)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 1, 0, 1, 1)
        self.cmdINFOASRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOASRC.setObjectName("cmdINFOASRC")
        self.gridLayout.addWidget(self.cmdINFOASRC, 1, 1, 1, 1)
        self.cmdINFOAPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOAPOL.setObjectName("cmdINFOAPOL")
        self.gridLayout.addWidget(self.cmdINFOAPOL, 1, 2, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_13)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 2, 0, 1, 1)
        self.cmdINFOBSRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOBSRC.setObjectName("cmdINFOBSRC")
        self.gridLayout.addWidget(self.cmdINFOBSRC, 2, 1, 1, 1)
        self.cmdINFOBPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOBPOL.setObjectName("cmdINFOBPOL")
        self.gridLayout.addWidget(self.cmdINFOBPOL, 2, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_13)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 3, 0, 1, 1)
        self.cmdINFOCSRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOCSRC.setObjectName("cmdINFOCSRC")
        self.gridLayout.addWidget(self.cmdINFOCSRC, 3, 1, 1, 1)
        self.cmdINFOCPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOCPOL.setObjectName("cmdINFOCPOL")
        self.gridLayout.addWidget(self.cmdINFOCPOL, 3, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 4, 2, 1, 1)
        self.gridlayout3.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setMargin(2)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.btnSetPos = QtGui.QPushButton(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetPos.sizePolicy().hasHeightForWidth())
        self.btnSetPos.setSizePolicy(sizePolicy)
        self.btnSetPos.setMinimumSize(QtCore.QSize(30, 0))
        self.btnSetPos.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnSetPos.setObjectName("btnSetPos")
        self.gridlayout4.addWidget(self.btnSetPos, 1, 1, 1, 1)
        self.textLabel3_6 = QtGui.QLabel(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_6.setFont(font)
        self.textLabel3_6.setObjectName("textLabel3_6")
        self.gridlayout4.addWidget(self.textLabel3_6, 0, 0, 1, 2)
        self.cb_pos_sel = QtGui.QComboBox(self.tab_TuneAndTesting)
        self.cb_pos_sel.setObjectName("cb_pos_sel")
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.cb_pos_sel.addItem(QtCore.QString())
        self.gridlayout4.addWidget(self.cb_pos_sel, 0, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem7, 0, 2, 1, 1)
        self.txtPos = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtPos.setObjectName("txtPos")
        self.gridlayout4.addWidget(self.txtPos, 1, 3, 1, 1)
        self.LCDPositionTest = QtGui.QLCDNumber(self.tab_TuneAndTesting)
        self.LCDPositionTest.setMinimumSize(QtCore.QSize(0, 40))
        self.LCDPositionTest.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDPositionTest.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDPositionTest.setFont(font)
        self.LCDPositionTest.setAutoFillBackground(True)
        self.LCDPositionTest.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDPositionTest.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDPositionTest.setNumDigits(14)
        self.LCDPositionTest.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDPositionTest.setObjectName("LCDPositionTest")
        self.gridlayout4.addWidget(self.LCDPositionTest, 2, 1, 1, 3)
        self.vboxlayout1.addLayout(self.gridlayout4)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem8)
        self.line_2 = QtGui.QFrame(self.tab_TuneAndTesting)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vboxlayout1.addWidget(self.line_2)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem9)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setMargin(2)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")
        self.btnSetEnc = QtGui.QPushButton(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetEnc.sizePolicy().hasHeightForWidth())
        self.btnSetEnc.setSizePolicy(sizePolicy)
        self.btnSetEnc.setMinimumSize(QtCore.QSize(30, 0))
        self.btnSetEnc.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnSetEnc.setObjectName("btnSetEnc")
        self.gridlayout5.addWidget(self.btnSetEnc, 1, 1, 1, 1)
        self.textLabel3_5 = QtGui.QLabel(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_5.setFont(font)
        self.textLabel3_5.setObjectName("textLabel3_5")
        self.gridlayout5.addWidget(self.textLabel3_5, 0, 0, 1, 2)
        self.cb_enc_sel = QtGui.QComboBox(self.tab_TuneAndTesting)
        self.cb_enc_sel.setObjectName("cb_enc_sel")
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.cb_enc_sel.addItem(QtCore.QString())
        self.gridlayout5.addWidget(self.cb_enc_sel, 0, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem10, 0, 2, 1, 1)
        self.txtEnc = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtEnc.setObjectName("txtEnc")
        self.gridlayout5.addWidget(self.txtEnc, 1, 3, 1, 1)
        self.LCDEncoder = QtGui.QLCDNumber(self.tab_TuneAndTesting)
        self.LCDEncoder.setMinimumSize(QtCore.QSize(0, 40))
        self.LCDEncoder.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDEncoder.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDEncoder.setFont(font)
        self.LCDEncoder.setAutoFillBackground(True)
        self.LCDEncoder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDEncoder.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDEncoder.setNumDigits(14)
        self.LCDEncoder.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDEncoder.setObjectName("LCDEncoder")
        self.gridlayout5.addWidget(self.LCDEncoder, 2, 1, 1, 3)
        self.vboxlayout1.addLayout(self.gridlayout5)
        self.gridlayout3.addLayout(self.vboxlayout1, 0, 1, 2, 2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem11, 2, 0, 1, 2)
        self.gridlayout6 = QtGui.QGridLayout()
        self.gridlayout6.setMargin(0)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")
        self.cmdAUXPS = QtGui.QCheckBox(self.tab_TuneAndTesting)
        self.cmdAUXPS.setObjectName("cmdAUXPS")
        self.gridlayout6.addWidget(self.cmdAUXPS, 1, 0, 1, 3)
        self.cmdINDEXER = QtGui.QComboBox(self.tab_TuneAndTesting)
        self.cmdINDEXER.setObjectName("cmdINDEXER")
        self.gridlayout6.addWidget(self.cmdINDEXER, 2, 1, 1, 2)
        self.textLabel3_4 = QtGui.QLabel(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_4.setFont(font)
        self.textLabel3_4.setObjectName("textLabel3_4")
        self.gridlayout6.addWidget(self.textLabel3_4, 2, 0, 1, 1)
        self.gridlayout3.addLayout(self.gridlayout6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_TuneAndTesting, "")
        self.gridlayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(PageiPapDriver)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.cb_enc_sel.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(PageiPapDriver)

    def retranslateUi(self, PageiPapDriver):
        PageiPapDriver.setWindowTitle(QtGui.QApplication.translate("PageiPapDriver", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PageiPapDriver", "Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.dscDriverName.setText(QtGui.QApplication.translate("PageiPapDriver", "<DRIVER_NAME>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PageiPapDriver", "Active:", None, QtGui.QApplication.UnicodeUTF8))
        self.dscActive.setText(QtGui.QApplication.translate("PageiPapDriver", "<YES/NO>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBlink.setText(QtGui.QApplication.translate("PageiPapDriver", "blink driver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PageiPapDriver", "Last config:", None, QtGui.QApplication.UnicodeUTF8))
        self.dscSignature.setText(QtGui.QApplication.translate("PageiPapDriver", "<_DATE_>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6_4.setText(QtGui.QApplication.translate("PageiPapDriver", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:7pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Step</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6_5.setText(QtGui.QApplication.translate("PageiPapDriver", "Stat", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6_3.setText(QtGui.QApplication.translate("PageiPapDriver", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6.setText(QtGui.QApplication.translate("PageiPapDriver", "Limit+", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6_2.setText(QtGui.QApplication.translate("PageiPapDriver", "Limit-", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3_3_2.setText(QtGui.QApplication.translate("PageiPapDriver", "Acc. time (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("PageiPapDriver", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3_3.setText(QtGui.QApplication.translate("PageiPapDriver", "Speed (steps/sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnable.setText(QtGui.QApplication.translate("PageiPapDriver", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("PageiPapDriver", "Move absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PageiPapDriver", "Jog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PageiPapDriver", "Limit Switches setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PageiPapDriver", "Cswitch mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCSWITCH.setItemText(0, QtGui.QApplication.translate("PageiPapDriver", "NORMAL", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCSWITCH.setItemText(1, QtGui.QApplication.translate("PageiPapDriver", "SMART", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCSWITCH.setItemText(2, QtGui.QApplication.translate("PageiPapDriver", "STICKY", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSendCfg.setText(QtGui.QApplication.translate("PageiPapDriver", "Send Config to board", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveCfg.setText(QtGui.QApplication.translate("PageiPapDriver", "Validate Config", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUndo.setText(QtGui.QApplication.translate("PageiPapDriver", "Discard changes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRestore.setText(QtGui.QApplication.translate("PageiPapDriver", "Reload board config", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("PageiPapDriver", "Info Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("PageiPapDriver", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("PageiPapDriver", "Polarity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("PageiPapDriver", "InfoA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("PageiPapDriver", "InfoB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("PageiPapDriver", "InfoC", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetPos.setText(QtGui.QApplication.translate("PageiPapDriver", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_6.setText(QtGui.QApplication.translate("PageiPapDriver", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(0, QtGui.QApplication.translate("PageiPapDriver", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(1, QtGui.QApplication.translate("PageiPapDriver", "Indexer", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(2, QtGui.QApplication.translate("PageiPapDriver", "ExtErr", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(3, QtGui.QApplication.translate("PageiPapDriver", "ShftEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(4, QtGui.QApplication.translate("PageiPapDriver", "TgtEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(5, QtGui.QApplication.translate("PageiPapDriver", "EncIn", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(6, QtGui.QApplication.translate("PageiPapDriver", "InPos", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pos_sel.setItemText(7, QtGui.QApplication.translate("PageiPapDriver", "AbsEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetEnc.setText(QtGui.QApplication.translate("PageiPapDriver", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_5.setText(QtGui.QApplication.translate("PageiPapDriver", "Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(0, QtGui.QApplication.translate("PageiPapDriver", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(1, QtGui.QApplication.translate("PageiPapDriver", "Indexer", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(2, QtGui.QApplication.translate("PageiPapDriver", "ExtErr", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(3, QtGui.QApplication.translate("PageiPapDriver", "ShftEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(4, QtGui.QApplication.translate("PageiPapDriver", "TgtEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(5, QtGui.QApplication.translate("PageiPapDriver", "EncIn", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(6, QtGui.QApplication.translate("PageiPapDriver", "InPos", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enc_sel.setItemText(7, QtGui.QApplication.translate("PageiPapDriver", "AbsEnc", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAUXPS.setText(QtGui.QApplication.translate("PageiPapDriver", "Aux Supply 5V", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_4.setText(QtGui.QApplication.translate("PageiPapDriver", "Indexer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_TuneAndTesting), QtGui.QApplication.translate("PageiPapDriver", "Tune and testing", None, QtGui.QApplication.UnicodeUTF8))

from Led import Led
from historiccfgwidget import HistoricCfgWidget
import icepapcms_rc
