# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'axis.ui'
#
# Created: Fri Feb  9 13:20:39 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_axis(object):
    def setupUi(self, axis):
        axis.setObjectName(_fromUtf8("axis"))
        axis.resize(575, 470)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(axis.sizePolicy().hasHeightForWidth())
        axis.setSizePolicy(sizePolicy)
        axis.setMinimumSize(QtCore.QSize(575, 470))
        axis.setSizeIncrement(QtCore.QSize(1, 1))
        self.gridLayout_5 = QtGui.QGridLayout(axis)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.axis_frame = QtGui.QFrame(axis)
        self.axis_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.axis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.axis_frame.setObjectName(_fromUtf8("axis_frame"))
        self.gridlayout = QtGui.QGridLayout(self.axis_frame)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.frame = QtGui.QFrame(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(30, 30))
        self.frame.setBaseSize(QtCore.QSize(192, 197))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cfgACTIVE = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgACTIVE.sizePolicy().hasHeightForWidth())
        self.cfgACTIVE.setSizePolicy(sizePolicy)
        self.cfgACTIVE.setMinimumSize(QtCore.QSize(60, 16))
        self.cfgACTIVE.setBaseSize(QtCore.QSize(66, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cfgACTIVE.setFont(font)
        self.cfgACTIVE.setObjectName(_fromUtf8("cfgACTIVE"))
        self.horizontalLayout.addWidget(self.cfgACTIVE)
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(55, 16))
        self.label.setBaseSize(QtCore.QSize(39, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cfgPROTLEVEL = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgPROTLEVEL.sizePolicy().hasHeightForWidth())
        self.cfgPROTLEVEL.setSizePolicy(sizePolicy)
        self.cfgPROTLEVEL.setMinimumSize(QtCore.QSize(50, 22))
        self.cfgPROTLEVEL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgPROTLEVEL.setMouseTracking(False)
        self.cfgPROTLEVEL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cfgPROTLEVEL.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cfgPROTLEVEL.setAutoFillBackground(False)
        self.cfgPROTLEVEL.setMaximum(999999999)
        self.cfgPROTLEVEL.setProperty("editable", True)
        self.cfgPROTLEVEL.setObjectName(_fromUtf8("cfgPROTLEVEL"))
        self.horizontalLayout.addWidget(self.cfgPROTLEVEL)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(25, 16))
        self.label_2.setBaseSize(QtCore.QSize(39, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtDriverName = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDriverName.sizePolicy().hasHeightForWidth())
        self.txtDriverName.setSizePolicy(sizePolicy)
        self.txtDriverName.setMinimumSize(QtCore.QSize(75, 22))
        self.txtDriverName.setMaximumSize(QtCore.QSize(16777215, 22))
        self.txtDriverName.setBaseSize(QtCore.QSize(100, 20))
        self.txtDriverName.setObjectName(_fromUtf8("txtDriverName"))
        self.horizontalLayout_2.addWidget(self.txtDriverName)
        self.cfgNAMELOCK = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgNAMELOCK.sizePolicy().hasHeightForWidth())
        self.cfgNAMELOCK.setSizePolicy(sizePolicy)
        self.cfgNAMELOCK.setMinimumSize(QtCore.QSize(110, 16))
        self.cfgNAMELOCK.setBaseSize(QtCore.QSize(66, 18))
        self.cfgNAMELOCK.setObjectName(_fromUtf8("cfgNAMELOCK"))
        self.horizontalLayout_2.addWidget(self.cfgNAMELOCK)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(44, 16))
        self.label_3.setBaseSize(QtCore.QSize(39, 16))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(5, 50))
        self.line.setBaseSize(QtCore.QSize(10, 61))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cfgANSTEP = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgANSTEP.sizePolicy().hasHeightForWidth())
        self.cfgANSTEP.setSizePolicy(sizePolicy)
        self.cfgANSTEP.setMinimumSize(QtCore.QSize(50, 22))
        self.cfgANSTEP.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgANSTEP.setBaseSize(QtCore.QSize(80, 16))
        self.cfgANSTEP.setWrapping(False)
        self.cfgANSTEP.setMaximum(999999999)
        self.cfgANSTEP.setObjectName(_fromUtf8("cfgANSTEP"))
        self.gridLayout_2.addWidget(self.cfgANSTEP, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 16))
        self.label_4.setBaseSize(QtCore.QSize(39, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.cfgANTURN = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgANTURN.sizePolicy().hasHeightForWidth())
        self.cfgANTURN.setSizePolicy(sizePolicy)
        self.cfgANTURN.setMinimumSize(QtCore.QSize(50, 22))
        self.cfgANTURN.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgANTURN.setBaseSize(QtCore.QSize(80, 16))
        self.cfgANTURN.setMaximum(999999999)
        self.cfgANTURN.setObjectName(_fromUtf8("cfgANTURN"))
        self.gridLayout_2.addWidget(self.cfgANTURN, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 16))
        self.label_5.setBaseSize(QtCore.QSize(39, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(70, 16))
        self.label_7.setBaseSize(QtCore.QSize(50, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.cfgINDEXER = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgINDEXER.sizePolicy().hasHeightForWidth())
        self.cfgINDEXER.setSizePolicy(sizePolicy)
        self.cfgINDEXER.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgINDEXER.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgINDEXER.setObjectName(_fromUtf8("cfgINDEXER"))
        self.gridLayout_3.addWidget(self.cfgINDEXER, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(100, 16))
        self.label_18.setBaseSize(QtCore.QSize(50, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.cfgLNKNAME = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgLNKNAME.sizePolicy().hasHeightForWidth())
        self.cfgLNKNAME.setSizePolicy(sizePolicy)
        self.cfgLNKNAME.setMinimumSize(QtCore.QSize(75, 22))
        self.cfgLNKNAME.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgLNKNAME.setBaseSize(QtCore.QSize(100, 20))
        self.cfgLNKNAME.setObjectName(_fromUtf8("cfgLNKNAME"))
        self.gridLayout_3.addWidget(self.cfgLNKNAME, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(186, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 6, 0, 1, 1)
        self.gridlayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(178, 100))
        self.frame_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.frame_2.setBaseSize(QtCore.QSize(178, 174))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(65, 16))
        self.label_10.setBaseSize(QtCore.QSize(50, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.hboxlayout.addWidget(self.label_10)
        self.txtMotorType = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMotorType.sizePolicy().hasHeightForWidth())
        self.txtMotorType.setSizePolicy(sizePolicy)
        self.txtMotorType.setMinimumSize(QtCore.QSize(100, 16))
        self.txtMotorType.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtMotorType.setBaseSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtMotorType.setFont(font)
        self.txtMotorType.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtMotorType.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtMotorType.setText(_fromUtf8(""))
        self.txtMotorType.setTextFormat(QtCore.Qt.PlainText)
        self.txtMotorType.setScaledContents(True)
        self.txtMotorType.setObjectName(_fromUtf8("txtMotorType"))
        self.hboxlayout.addWidget(self.txtMotorType)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(10)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(70, 16))
        self.label_11.setBaseSize(QtCore.QSize(50, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.hboxlayout1.addWidget(self.label_11)
        self.txtNCURR = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNCURR.sizePolicy().hasHeightForWidth())
        self.txtNCURR.setSizePolicy(sizePolicy)
        self.txtNCURR.setMinimumSize(QtCore.QSize(30, 16))
        self.txtNCURR.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtNCURR.setBaseSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtNCURR.setFont(font)
        self.txtNCURR.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtNCURR.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtNCURR.setText(_fromUtf8(""))
        self.txtNCURR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtNCURR.setObjectName(_fromUtf8("txtNCURR"))
        self.hboxlayout1.addWidget(self.txtNCURR)
        self.label_12 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(40, 16))
        self.label_12.setBaseSize(QtCore.QSize(40, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.hboxlayout1.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.hboxlayout1)
        self.cfgPOWERON = QtGui.QCheckBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgPOWERON.sizePolicy().hasHeightForWidth())
        self.cfgPOWERON.setSizePolicy(sizePolicy)
        self.cfgPOWERON.setMinimumSize(QtCore.QSize(160, 16))
        self.cfgPOWERON.setBaseSize(QtCore.QSize(220, 18))
        self.cfgPOWERON.setObjectName(_fromUtf8("cfgPOWERON"))
        self.verticalLayout.addWidget(self.cfgPOWERON)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(70, 16))
        self.label_13.setBaseSize(QtCore.QSize(100, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.hboxlayout2.addWidget(self.label_13)
        self.cfgMOTSENSE = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgMOTSENSE.sizePolicy().hasHeightForWidth())
        self.cfgMOTSENSE.setSizePolicy(sizePolicy)
        self.cfgMOTSENSE.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgMOTSENSE.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgMOTSENSE.setBaseSize(QtCore.QSize(80, 16))
        self.cfgMOTSENSE.setObjectName(_fromUtf8("cfgMOTSENSE"))
        self.hboxlayout2.addWidget(self.cfgMOTSENSE)
        self.verticalLayout.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(30, 16))
        self.label_14.setBaseSize(QtCore.QSize(40, 16))
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.hboxlayout3.addWidget(self.label_14)
        self.line_2 = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.hboxlayout3.addWidget(self.line_2)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(30, 16))
        self.label_15.setBaseSize(QtCore.QSize(40, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridlayout1.addWidget(self.label_15, 0, 0, 1, 1)
        self.cfgLPPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgLPPOL.sizePolicy().hasHeightForWidth())
        self.cfgLPPOL.setSizePolicy(sizePolicy)
        self.cfgLPPOL.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgLPPOL.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgLPPOL.setObjectName(_fromUtf8("cfgLPPOL"))
        self.gridlayout1.addWidget(self.cfgLPPOL, 0, 1, 1, 1)
        self.cfgLMPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgLMPOL.sizePolicy().hasHeightForWidth())
        self.cfgLMPOL.setSizePolicy(sizePolicy)
        self.cfgLMPOL.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgLMPOL.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgLMPOL.setObjectName(_fromUtf8("cfgLMPOL"))
        self.gridlayout1.addWidget(self.cfgLMPOL, 1, 1, 1, 1)
        self.cfgHOMEPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEPOL.sizePolicy().hasHeightForWidth())
        self.cfgHOMEPOL.setSizePolicy(sizePolicy)
        self.cfgHOMEPOL.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgHOMEPOL.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgHOMEPOL.setObjectName(_fromUtf8("cfgHOMEPOL"))
        self.gridlayout1.addWidget(self.cfgHOMEPOL, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(30, 16))
        self.label_17.setBaseSize(QtCore.QSize(40, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridlayout1.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(30, 16))
        self.label_26.setBaseSize(QtCore.QSize(40, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridlayout1.addWidget(self.label_26, 1, 0, 1, 1)
        self.hboxlayout3.addLayout(self.gridlayout1)
        self.verticalLayout.addLayout(self.hboxlayout3)
        self.gridlayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 68))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox.setBaseSize(QtCore.QSize(192, 68))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(130, 16))
        self.label_8.setMaximumSize(QtCore.QSize(130, 40))
        self.label_8.setBaseSize(QtCore.QSize(70, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.cfgDEFVEL = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgDEFVEL.sizePolicy().hasHeightForWidth())
        self.cfgDEFVEL.setSizePolicy(sizePolicy)
        self.cfgDEFVEL.setMinimumSize(QtCore.QSize(50, 22))
        self.cfgDEFVEL.setMaximumSize(QtCore.QSize(100, 22))
        self.cfgDEFVEL.setBaseSize(QtCore.QSize(80, 16))
        self.cfgDEFVEL.setMaximum(999999999.0)
        self.cfgDEFVEL.setSingleStep(0.01)
        self.cfgDEFVEL.setObjectName(_fromUtf8("cfgDEFVEL"))
        self.gridLayout.addWidget(self.cfgDEFVEL, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(85, 16))
        self.label_9.setMaximumSize(QtCore.QSize(125, 40))
        self.label_9.setBaseSize(QtCore.QSize(70, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.cfgDEFACCT = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgDEFACCT.sizePolicy().hasHeightForWidth())
        self.cfgDEFACCT.setSizePolicy(sizePolicy)
        self.cfgDEFACCT.setMinimumSize(QtCore.QSize(50, 22))
        self.cfgDEFACCT.setMaximumSize(QtCore.QSize(100, 22))
        self.cfgDEFACCT.setBaseSize(QtCore.QSize(80, 16))
        self.cfgDEFACCT.setMaximum(999999999.0)
        self.cfgDEFACCT.setSingleStep(0.01)
        self.cfgDEFACCT.setObjectName(_fromUtf8("cfgDEFACCT"))
        self.gridLayout.addWidget(self.cfgDEFACCT, 1, 1, 1, 1)
        self.gridlayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(178, 80))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox_2.setBaseSize(QtCore.QSize(178, 80))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setContentsMargins(5, 0, 5, 5)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(100, 16))
        self.label_20.setBaseSize(QtCore.QSize(100, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridlayout2.addWidget(self.label_20, 0, 0, 1, 1)
        self.cfgTGTENC = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgTGTENC.sizePolicy().hasHeightForWidth())
        self.cfgTGTENC.setSizePolicy(sizePolicy)
        self.cfgTGTENC.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgTGTENC.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgTGTENC.setBaseSize(QtCore.QSize(80, 16))
        self.cfgTGTENC.setObjectName(_fromUtf8("cfgTGTENC"))
        self.gridlayout2.addWidget(self.cfgTGTENC, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(90, 16))
        self.label_21.setBaseSize(QtCore.QSize(100, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridlayout2.addWidget(self.label_21, 1, 0, 1, 1)
        self.cfgSHFTENC = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgSHFTENC.sizePolicy().hasHeightForWidth())
        self.cfgSHFTENC.setSizePolicy(sizePolicy)
        self.cfgSHFTENC.setMinimumSize(QtCore.QSize(80, 22))
        self.cfgSHFTENC.setMaximumSize(QtCore.QSize(80, 22))
        self.cfgSHFTENC.setBaseSize(QtCore.QSize(80, 16))
        self.cfgSHFTENC.setObjectName(_fromUtf8("cfgSHFTENC"))
        self.gridlayout2.addWidget(self.cfgSHFTENC, 1, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout2)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(80, 16))
        self.label_22.setBaseSize(QtCore.QSize(100, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridlayout3.addWidget(self.label_22, 0, 0, 1, 1)
        self.txtPCLOOP = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPCLOOP.sizePolicy().hasHeightForWidth())
        self.txtPCLOOP.setSizePolicy(sizePolicy)
        self.txtPCLOOP.setMinimumSize(QtCore.QSize(60, 16))
        self.txtPCLOOP.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtPCLOOP.setBaseSize(QtCore.QSize(80, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtPCLOOP.setFont(font)
        self.txtPCLOOP.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtPCLOOP.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtPCLOOP.setText(_fromUtf8(""))
        self.txtPCLOOP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPCLOOP.setObjectName(_fromUtf8("txtPCLOOP"))
        self.gridlayout3.addWidget(self.txtPCLOOP, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(100, 16))
        self.label_23.setBaseSize(QtCore.QSize(100, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridlayout3.addWidget(self.label_23, 1, 0, 1, 1)
        self.txtCTRLENC = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCTRLENC.sizePolicy().hasHeightForWidth())
        self.txtCTRLENC.setSizePolicy(sizePolicy)
        self.txtCTRLENC.setMinimumSize(QtCore.QSize(60, 16))
        self.txtCTRLENC.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtCTRLENC.setBaseSize(QtCore.QSize(80, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtCTRLENC.setFont(font)
        self.txtCTRLENC.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtCTRLENC.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtCTRLENC.setText(_fromUtf8(""))
        self.txtCTRLENC.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCTRLENC.setObjectName(_fromUtf8("txtCTRLENC"))
        self.gridlayout3.addWidget(self.txtCTRLENC, 1, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout3)
        self.gridlayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.axis_frame, 0, 0, 2, 2)
        spacerItem1 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 2, 1, 1, 1)

        self.retranslateUi(axis)
        QtCore.QMetaObject.connectSlotsByName(axis)

    def retranslateUi(self, axis):
        axis.setWindowTitle(_translate("axis", "Dialog", None))
        self.cfgACTIVE.setText(_translate("axis", "Active axis", None))
        self.label.setText(_translate("axis", "Protection", None))
        self.label_2.setText(_translate("axis", "Name", None))
        self.cfgNAMELOCK.setText(_translate("axis", "Lock name", None))
        self.label_3.setText(_translate("axis", "Movement resolution", None))
        self.label_4.setText(_translate("axis", "steps in", None))
        self.label_5.setText(_translate("axis", "turn(s)", None))
        self.label_7.setText(_translate("axis", "Default indexer", None))
        self.label_18.setText(_translate("axis", "Linked Axis name", None))
        self.label_10.setText(_translate("axis", "Motor type", None))
        self.label_11.setText(_translate("axis", "Nominal current:", None))
        self.label_12.setText(_translate("axis", "Amps", None))
        self.cfgPOWERON.setText(_translate("axis", "Restore power state at power on", None))
        self.label_13.setText(_translate("axis", "Motor direction", None))
        self.label_14.setText(_translate("axis", "Switch polarity", None))
        self.label_15.setText(_translate("axis", "Limit+", None))
        self.label_17.setText(_translate("axis", "Home", None))
        self.label_26.setText(_translate("axis", "Limit-", None))
        self.groupBox.setTitle(_translate("axis", "Default motion values", None))
        self.label_8.setText(_translate("axis", "Velocity (steps/s)", None))
        self.label_9.setText(_translate("axis", "Acceleration time(s)", None))
        self.groupBox_2.setTitle(_translate("axis", "Functional Encoders", None))
        self.label_20.setText(_translate("axis", "Target Encoder", None))
        self.label_21.setText(_translate("axis", "Shaft Encoder", None))
        self.label_22.setText(_translate("axis", "Closed loop:", None))
        self.label_23.setText(_translate("axis", "Position control", None))

