# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogipapprogram.ui'
#
# Created: Fri Feb  9 13:20:39 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogIcepapProgram(object):
    def setupUi(self, DialogIcepapProgram):
        DialogIcepapProgram.setObjectName(_fromUtf8("DialogIcepapProgram"))
        DialogIcepapProgram.resize(475, 239)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        DialogIcepapProgram.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addFile(_fromUtf8(":/icons/IcepapCfg Icons/gnome-cpu.png"))
        DialogIcepapProgram.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(DialogIcepapProgram)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.txtHost = QtGui.QLineEdit(DialogIcepapProgram)
        self.txtHost.setObjectName(_fromUtf8("txtHost"))
        self.gridlayout.addWidget(self.txtHost, 2, 6, 1, 2)
        self.cbProgram = QtGui.QComboBox(DialogIcepapProgram)
        self.cbProgram.setObjectName(_fromUtf8("cbProgram"))
        self.cbProgram.addItem(_fromUtf8(""))
        self.cbProgram.addItem(_fromUtf8(""))
        self.cbProgram.addItem(_fromUtf8(""))
        self.cbProgram.addItem(_fromUtf8(""))
        self.cbProgram.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cbProgram, 1, 1, 1, 1)
        self.btnProgram = QtGui.QPushButton(DialogIcepapProgram)
        self.btnProgram.setIcon(icon)
        self.btnProgram.setObjectName(_fromUtf8("btnProgram"))
        self.gridlayout.addWidget(self.btnProgram, 5, 5, 1, 3)
        self.rbSerial = QtGui.QRadioButton(DialogIcepapProgram)
        self.rbSerial.setObjectName(_fromUtf8("rbSerial"))
        self.gridlayout.addWidget(self.rbSerial, 1, 4, 1, 2)
        self.label = QtGui.QLabel(DialogIcepapProgram)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.cbSerial = QtGui.QComboBox(DialogIcepapProgram)
        self.cbSerial.setObjectName(_fromUtf8("cbSerial"))
        self.gridlayout.addWidget(self.cbSerial, 1, 6, 1, 2)
        self.btnClose = QtGui.QPushButton(DialogIcepapProgram)
        icon1 = QtGui.QIcon()
        icon1.addFile(_fromUtf8(":/icons/IcepapCfg Icons/close.png"))
        self.btnClose.setIcon(icon1)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridlayout.addWidget(self.btnClose, 6, 5, 1, 3)
        self.label_2 = QtGui.QLabel(DialogIcepapProgram)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnBrowser = QtGui.QToolButton(DialogIcepapProgram)
        self.btnBrowser.setObjectName(_fromUtf8("btnBrowser"))
        self.gridlayout.addWidget(self.btnBrowser, 0, 7, 1, 1)
        self.btnTest = QtGui.QPushButton(DialogIcepapProgram)
        icon2 = QtGui.QIcon()
        icon2.addFile(_fromUtf8(":/icons/IcepapCfg Icons/gnome-nettool.png"))
        self.btnTest.setIcon(icon2)
        self.btnTest.setObjectName(_fromUtf8("btnTest"))
        self.gridlayout.addWidget(self.btnTest, 4, 5, 1, 3)
        self.rbEth = QtGui.QRadioButton(DialogIcepapProgram)
        self.rbEth.setObjectName(_fromUtf8("rbEth"))
        self.gridlayout.addWidget(self.rbEth, 2, 4, 1, 2)
        self.label_3 = QtGui.QLabel(DialogIcepapProgram)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 4, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 3, 6, 1, 1)
        self.sbAddr = QtGui.QSpinBox(DialogIcepapProgram)
        self.sbAddr.setMinimum(1)
        self.sbAddr.setMaximum(128)
        self.sbAddr.setObjectName(_fromUtf8("sbAddr"))
        self.gridlayout.addWidget(self.sbAddr, 1, 2, 1, 1)
        self.cbOptions = QtGui.QComboBox(DialogIcepapProgram)
        self.cbOptions.setObjectName(_fromUtf8("cbOptions"))
        self.cbOptions.addItem(_fromUtf8(""))
        self.cbOptions.addItem(_fromUtf8(""))
        self.cbOptions.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cbOptions, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.txtFirmwareFile = QtGui.QLineEdit(DialogIcepapProgram)
        self.txtFirmwareFile.setMaximumSize(QtCore.QSize(1666666, 16777215))
        self.txtFirmwareFile.setObjectName(_fromUtf8("txtFirmwareFile"))
        self.gridlayout.addWidget(self.txtFirmwareFile, 0, 1, 1, 6)
        self.txtLog = QtGui.QTextEdit(DialogIcepapProgram)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtLog.setFont(font)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName(_fromUtf8("txtLog"))
        self.gridlayout.addWidget(self.txtLog, 3, 0, 4, 4)
        self.chkForce = QtGui.QCheckBox(DialogIcepapProgram)
        self.chkForce.setObjectName(_fromUtf8("chkForce"))
        self.gridlayout.addWidget(self.chkForce, 2, 2, 1, 1)

        self.retranslateUi(DialogIcepapProgram)
        QtCore.QMetaObject.connectSlotsByName(DialogIcepapProgram)
        DialogIcepapProgram.setTabOrder(self.txtFirmwareFile, self.btnBrowser)
        DialogIcepapProgram.setTabOrder(self.btnBrowser, self.cbProgram)
        DialogIcepapProgram.setTabOrder(self.cbProgram, self.sbAddr)
        DialogIcepapProgram.setTabOrder(self.sbAddr, self.cbOptions)
        DialogIcepapProgram.setTabOrder(self.cbOptions, self.rbSerial)
        DialogIcepapProgram.setTabOrder(self.rbSerial, self.rbEth)
        DialogIcepapProgram.setTabOrder(self.rbEth, self.cbSerial)
        DialogIcepapProgram.setTabOrder(self.cbSerial, self.txtHost)
        DialogIcepapProgram.setTabOrder(self.txtHost, self.btnTest)
        DialogIcepapProgram.setTabOrder(self.btnTest, self.btnProgram)
        DialogIcepapProgram.setTabOrder(self.btnProgram, self.btnClose)
        DialogIcepapProgram.setTabOrder(self.btnClose, self.txtLog)

    def retranslateUi(self, DialogIcepapProgram):
        DialogIcepapProgram.setWindowTitle(_translate("DialogIcepapProgram", "Icepap Program", None))
        self.cbProgram.setItemText(0, _translate("DialogIcepapProgram", "NONE", None))
        self.cbProgram.setItemText(1, _translate("DialogIcepapProgram", "ALL", None))
        self.cbProgram.setItemText(2, _translate("DialogIcepapProgram", "DRIVERS", None))
        self.cbProgram.setItemText(3, _translate("DialogIcepapProgram", "COMM", None))
        self.cbProgram.setItemText(4, _translate("DialogIcepapProgram", "ADDR", None))
        self.btnProgram.setText(_translate("DialogIcepapProgram", "Upgrade firmware", None))
        self.rbSerial.setText(_translate("DialogIcepapProgram", "Serial Line", None))
        self.label.setText(_translate("DialogIcepapProgram", "Firmware file", None))
        self.btnClose.setText(_translate("DialogIcepapProgram", "OK", None))
        self.label_2.setText(_translate("DialogIcepapProgram", "Program", None))
        self.btnBrowser.setText(_translate("DialogIcepapProgram", "...", None))
        self.btnTest.setText(_translate("DialogIcepapProgram", "Test connection", None))
        self.rbEth.setText(_translate("DialogIcepapProgram", "Ethernet", None))
        self.label_3.setText(_translate("DialogIcepapProgram", "Options", None))
        self.cbOptions.setItemText(0, _translate("DialogIcepapProgram", "SAVE", None))
        self.cbOptions.setItemText(1, _translate("DialogIcepapProgram", "SL", None))
        self.cbOptions.setItemText(2, _translate("DialogIcepapProgram", "NONE", None))
        self.chkForce.setText(_translate("DialogIcepapProgram", "Force", None))

import icepapcms_rc
