# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialoghomesrch.ui'
#
# Created: Fri Dec  7 12:47:51 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogHomeSrch(object):
    def setupUi(self, DialogHomeSrch):
        DialogHomeSrch.setObjectName(_fromUtf8("DialogHomeSrch"))
        DialogHomeSrch.resize(605, 266)
        self.verticalLayout = QtGui.QVBoxLayout(DialogHomeSrch)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cbHomeSearch = QtGui.QComboBox(DialogHomeSrch)
        self.cbHomeSearch.setMinimumSize(QtCore.QSize(100, 0))
        self.cbHomeSearch.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbHomeSearch.setObjectName(_fromUtf8("cbHomeSearch"))
        self.cbHomeSearch.addItem(_fromUtf8(""))
        self.cbHomeSearch.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbHomeSearch)
        self.cbHsOptions = QtGui.QComboBox(DialogHomeSrch)
        self.cbHsOptions.setObjectName(_fromUtf8("cbHsOptions"))
        self.verticalLayout_2.addWidget(self.cbHsOptions)
        self.cbEdge = QtGui.QComboBox(DialogHomeSrch)
        self.cbEdge.setObjectName(_fromUtf8("cbEdge"))
        self.cbEdge.addItem(_fromUtf8(""))
        self.cbEdge.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbEdge)
        self.cbDirection = QtGui.QComboBox(DialogHomeSrch)
        self.cbDirection.setObjectName(_fromUtf8("cbDirection"))
        self.cbDirection.addItem(_fromUtf8(""))
        self.cbDirection.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbDirection)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnGoStop = QtGui.QPushButton(DialogHomeSrch)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnGoStop.setFont(font)
        self.btnGoStop.setText(_fromUtf8(""))
        self.btnGoStop.setObjectName(_fromUtf8("btnGoStop"))
        self.verticalLayout_2.addWidget(self.btnGoStop)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.frameValues = QtGui.QFrame(DialogHomeSrch)
        self.frameValues.setObjectName(_fromUtf8("frameValues"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameValues)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcdPosEncin = QtGui.QLCDNumber(self.frameValues)
        self.lcdPosEncin.setNumDigits(12)
        self.lcdPosEncin.setObjectName(_fromUtf8("lcdPosEncin"))
        self.gridLayout_2.addWidget(self.lcdPosEncin, 3, 1, 1, 1)
        self.lcdEncTgtenc = QtGui.QLCDNumber(self.frameValues)
        self.lcdEncTgtenc.setNumDigits(12)
        self.lcdEncTgtenc.setObjectName(_fromUtf8("lcdEncTgtenc"))
        self.gridLayout_2.addWidget(self.lcdEncTgtenc, 2, 2, 1, 1)
        self.lcdEncAbsenc = QtGui.QLCDNumber(self.frameValues)
        self.lcdEncAbsenc.setNumDigits(12)
        self.lcdEncAbsenc.setObjectName(_fromUtf8("lcdEncAbsenc"))
        self.gridLayout_2.addWidget(self.lcdEncAbsenc, 5, 2, 1, 1)
        self.lcdPosAbsenc = QtGui.QLCDNumber(self.frameValues)
        self.lcdPosAbsenc.setNumDigits(12)
        self.lcdPosAbsenc.setObjectName(_fromUtf8("lcdPosAbsenc"))
        self.gridLayout_2.addWidget(self.lcdPosAbsenc, 5, 1, 1, 1)
        self.lcdPosInpos = QtGui.QLCDNumber(self.frameValues)
        self.lcdPosInpos.setNumDigits(12)
        self.lcdPosInpos.setObjectName(_fromUtf8("lcdPosInpos"))
        self.gridLayout_2.addWidget(self.lcdPosInpos, 4, 1, 1, 1)
        self.lcdEncEncin = QtGui.QLCDNumber(self.frameValues)
        self.lcdEncEncin.setNumDigits(12)
        self.lcdEncEncin.setObjectName(_fromUtf8("lcdEncEncin"))
        self.gridLayout_2.addWidget(self.lcdEncEncin, 3, 2, 1, 1)
        self.lcdEncAxis = QtGui.QLCDNumber(self.frameValues)
        self.lcdEncAxis.setNumDigits(12)
        self.lcdEncAxis.setObjectName(_fromUtf8("lcdEncAxis"))
        self.gridLayout_2.addWidget(self.lcdEncAxis, 1, 2, 1, 1)
        self.lcdEncInpos = QtGui.QLCDNumber(self.frameValues)
        self.lcdEncInpos.setNumDigits(12)
        self.lcdEncInpos.setObjectName(_fromUtf8("lcdEncInpos"))
        self.gridLayout_2.addWidget(self.lcdEncInpos, 4, 2, 1, 1)
        self.labelEnc = QtGui.QLabel(self.frameValues)
        self.labelEnc.setMinimumSize(QtCore.QSize(200, 0))
        self.labelEnc.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelEnc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEnc.setObjectName(_fromUtf8("labelEnc"))
        self.gridLayout_2.addWidget(self.labelEnc, 0, 2, 1, 1)
        self.labelPos = QtGui.QLabel(self.frameValues)
        self.labelPos.setMinimumSize(QtCore.QSize(200, 0))
        self.labelPos.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelPos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPos.setObjectName(_fromUtf8("labelPos"))
        self.gridLayout_2.addWidget(self.labelPos, 0, 1, 1, 1)
        self.lcdPosTgtenc = QtGui.QLCDNumber(self.frameValues)
        self.lcdPosTgtenc.setNumDigits(12)
        self.lcdPosTgtenc.setObjectName(_fromUtf8("lcdPosTgtenc"))
        self.gridLayout_2.addWidget(self.lcdPosTgtenc, 2, 1, 1, 1)
        self.lcdPosAxis = QtGui.QLCDNumber(self.frameValues)
        self.lcdPosAxis.setNumDigits(12)
        self.lcdPosAxis.setObjectName(_fromUtf8("lcdPosAxis"))
        self.gridLayout_2.addWidget(self.lcdPosAxis, 1, 1, 1, 1)
        self.labelAbsenc = QtGui.QLabel(self.frameValues)
        self.labelAbsenc.setMinimumSize(QtCore.QSize(0, 30))
        self.labelAbsenc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelAbsenc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAbsenc.setObjectName(_fromUtf8("labelAbsenc"))
        self.gridLayout_2.addWidget(self.labelAbsenc, 5, 0, 1, 1)
        self.labelInpos = QtGui.QLabel(self.frameValues)
        self.labelInpos.setMinimumSize(QtCore.QSize(0, 30))
        self.labelInpos.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelInpos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInpos.setObjectName(_fromUtf8("labelInpos"))
        self.gridLayout_2.addWidget(self.labelInpos, 4, 0, 1, 1)
        self.labelEncin = QtGui.QLabel(self.frameValues)
        self.labelEncin.setMinimumSize(QtCore.QSize(0, 30))
        self.labelEncin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelEncin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEncin.setObjectName(_fromUtf8("labelEncin"))
        self.gridLayout_2.addWidget(self.labelEncin, 3, 0, 1, 1)
        self.labelTgtenc = QtGui.QLabel(self.frameValues)
        self.labelTgtenc.setMinimumSize(QtCore.QSize(0, 30))
        self.labelTgtenc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelTgtenc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTgtenc.setObjectName(_fromUtf8("labelTgtenc"))
        self.gridLayout_2.addWidget(self.labelTgtenc, 2, 0, 1, 1)
        self.labelAxis = QtGui.QLabel(self.frameValues)
        self.labelAxis.setMinimumSize(QtCore.QSize(0, 30))
        self.labelAxis.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelAxis.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAxis.setObjectName(_fromUtf8("labelAxis"))
        self.gridLayout_2.addWidget(self.labelAxis, 1, 0, 1, 1)
        self.gvIndicator = QtGui.QGraphicsView(self.frameValues)
        self.gvIndicator.setEnabled(True)
        self.gvIndicator.setMinimumSize(QtCore.QSize(60, 30))
        self.gvIndicator.setMaximumSize(QtCore.QSize(60, 30))
        self.gvIndicator.setAcceptDrops(False)
        self.gvIndicator.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvIndicator.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvIndicator.setObjectName(_fromUtf8("gvIndicator"))
        self.gridLayout_2.addWidget(self.gvIndicator, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frameValues)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bbClose = QtGui.QDialogButtonBox(DialogHomeSrch)
        self.bbClose.setOrientation(QtCore.Qt.Horizontal)
        self.bbClose.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.bbClose.setCenterButtons(True)
        self.bbClose.setObjectName(_fromUtf8("bbClose"))
        self.verticalLayout.addWidget(self.bbClose)

        self.retranslateUi(DialogHomeSrch)
        QtCore.QObject.connect(self.bbClose, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogHomeSrch.reject)
        QtCore.QObject.connect(self.bbClose, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogHomeSrch.accept)
        QtCore.QMetaObject.connectSlotsByName(DialogHomeSrch)

    def retranslateUi(self, DialogHomeSrch):
        DialogHomeSrch.setWindowTitle(_translate("DialogHomeSrch", "Home and Search", None))
        self.cbHomeSearch.setItemText(0, _translate("DialogHomeSrch", "HOME", None))
        self.cbHomeSearch.setItemText(1, _translate("DialogHomeSrch", "SRCH", None))
        self.cbEdge.setItemText(0, _translate("DialogHomeSrch", "POSEDGE", None))
        self.cbEdge.setItemText(1, _translate("DialogHomeSrch", "NEGEDGE", None))
        self.cbDirection.setItemText(0, _translate("DialogHomeSrch", "-1", None))
        self.cbDirection.setItemText(1, _translate("DialogHomeSrch", "+1", None))
        self.labelEnc.setText(_translate("DialogHomeSrch", "ENC", None))
        self.labelPos.setText(_translate("DialogHomeSrch", "POS", None))
        self.labelAbsenc.setText(_translate("DialogHomeSrch", "ABSENC", None))
        self.labelInpos.setText(_translate("DialogHomeSrch", "INPOS", None))
        self.labelEncin.setText(_translate("DialogHomeSrch", "ENCIN", None))
        self.labelTgtenc.setText(_translate("DialogHomeSrch", " TGTENC ", None))
        self.labelAxis.setText(_translate("DialogHomeSrch", "AXIS", None))

