# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialoghomesrch.ui'
#
# Created: Thu Dec  6 13:31:09 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogHomeSrch(object):
    def setupUi(self, DialogHomeSrch):
        DialogHomeSrch.setObjectName(_fromUtf8("DialogHomeSrch"))
        DialogHomeSrch.resize(605, 266)
        self.verticalLayout = QtGui.QVBoxLayout(DialogHomeSrch)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cbHomeSearch = QtGui.QComboBox(DialogHomeSrch)
        self.cbHomeSearch.setMinimumSize(QtCore.QSize(100, 0))
        self.cbHomeSearch.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbHomeSearch.setObjectName(_fromUtf8("cbHomeSearch"))
        self.cbHomeSearch.addItem(_fromUtf8(""))
        self.cbHomeSearch.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbHomeSearch)
        self.cbHsOptions = QtGui.QComboBox(DialogHomeSrch)
        self.cbHsOptions.setObjectName(_fromUtf8("cbHsOptions"))
        self.verticalLayout_2.addWidget(self.cbHsOptions)
        self.cbEdge = QtGui.QComboBox(DialogHomeSrch)
        self.cbEdge.setObjectName(_fromUtf8("cbEdge"))
        self.cbEdge.addItem(_fromUtf8(""))
        self.cbEdge.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbEdge)
        self.cbDirection = QtGui.QComboBox(DialogHomeSrch)
        self.cbDirection.setObjectName(_fromUtf8("cbDirection"))
        self.cbDirection.addItem(_fromUtf8(""))
        self.cbDirection.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbDirection)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnGo = QtGui.QPushButton(DialogHomeSrch)
        self.btnGo.setObjectName(_fromUtf8("btnGo"))
        self.verticalLayout_2.addWidget(self.btnGo)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcdEncinPos = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdEncinPos.setNumDigits(12)
        self.lcdEncinPos.setObjectName(_fromUtf8("lcdEncinPos"))
        self.gridLayout_2.addWidget(self.lcdEncinPos, 3, 1, 1, 1)
        self.lcdTgtencEnc = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdTgtencEnc.setNumDigits(12)
        self.lcdTgtencEnc.setObjectName(_fromUtf8("lcdTgtencEnc"))
        self.gridLayout_2.addWidget(self.lcdTgtencEnc, 2, 2, 1, 1)
        self.lcdAbsencEnc = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdAbsencEnc.setNumDigits(12)
        self.lcdAbsencEnc.setObjectName(_fromUtf8("lcdAbsencEnc"))
        self.gridLayout_2.addWidget(self.lcdAbsencEnc, 5, 2, 1, 1)
        self.lcdAbsencPos = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdAbsencPos.setNumDigits(12)
        self.lcdAbsencPos.setObjectName(_fromUtf8("lcdAbsencPos"))
        self.gridLayout_2.addWidget(self.lcdAbsencPos, 5, 1, 1, 1)
        self.lcdInposPos = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdInposPos.setNumDigits(12)
        self.lcdInposPos.setObjectName(_fromUtf8("lcdInposPos"))
        self.gridLayout_2.addWidget(self.lcdInposPos, 4, 1, 1, 1)
        self.lcdEncinEnc = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdEncinEnc.setNumDigits(12)
        self.lcdEncinEnc.setObjectName(_fromUtf8("lcdEncinEnc"))
        self.gridLayout_2.addWidget(self.lcdEncinEnc, 3, 2, 1, 1)
        self.lcdAxisEnc = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdAxisEnc.setNumDigits(12)
        self.lcdAxisEnc.setObjectName(_fromUtf8("lcdAxisEnc"))
        self.gridLayout_2.addWidget(self.lcdAxisEnc, 1, 2, 1, 1)
        self.lcdEnc = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdEnc.setNumDigits(12)
        self.lcdEnc.setObjectName(_fromUtf8("lcdEnc"))
        self.gridLayout_2.addWidget(self.lcdEnc, 4, 2, 1, 1)
        self.labelEnc = QtGui.QLabel(DialogHomeSrch)
        self.labelEnc.setMinimumSize(QtCore.QSize(200, 0))
        self.labelEnc.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelEnc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEnc.setObjectName(_fromUtf8("labelEnc"))
        self.gridLayout_2.addWidget(self.labelEnc, 0, 2, 1, 1)
        self.labelPos = QtGui.QLabel(DialogHomeSrch)
        self.labelPos.setMinimumSize(QtCore.QSize(200, 0))
        self.labelPos.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelPos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPos.setObjectName(_fromUtf8("labelPos"))
        self.gridLayout_2.addWidget(self.labelPos, 0, 1, 1, 1)
        self.lcdTgtencPos = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdTgtencPos.setNumDigits(12)
        self.lcdTgtencPos.setObjectName(_fromUtf8("lcdTgtencPos"))
        self.gridLayout_2.addWidget(self.lcdTgtencPos, 2, 1, 1, 1)
        self.lcdAxisPos = QtGui.QLCDNumber(DialogHomeSrch)
        self.lcdAxisPos.setNumDigits(12)
        self.lcdAxisPos.setObjectName(_fromUtf8("lcdAxisPos"))
        self.gridLayout_2.addWidget(self.lcdAxisPos, 1, 1, 1, 1)
        self.labelAbsenc = QtGui.QLabel(DialogHomeSrch)
        self.labelAbsenc.setMinimumSize(QtCore.QSize(0, 30))
        self.labelAbsenc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelAbsenc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAbsenc.setObjectName(_fromUtf8("labelAbsenc"))
        self.gridLayout_2.addWidget(self.labelAbsenc, 5, 0, 1, 1)
        self.labelInpos = QtGui.QLabel(DialogHomeSrch)
        self.labelInpos.setMinimumSize(QtCore.QSize(0, 30))
        self.labelInpos.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelInpos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInpos.setObjectName(_fromUtf8("labelInpos"))
        self.gridLayout_2.addWidget(self.labelInpos, 4, 0, 1, 1)
        self.labelEncin = QtGui.QLabel(DialogHomeSrch)
        self.labelEncin.setMinimumSize(QtCore.QSize(0, 30))
        self.labelEncin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelEncin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEncin.setObjectName(_fromUtf8("labelEncin"))
        self.gridLayout_2.addWidget(self.labelEncin, 3, 0, 1, 1)
        self.labelTgtenc = QtGui.QLabel(DialogHomeSrch)
        self.labelTgtenc.setMinimumSize(QtCore.QSize(0, 30))
        self.labelTgtenc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelTgtenc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTgtenc.setObjectName(_fromUtf8("labelTgtenc"))
        self.gridLayout_2.addWidget(self.labelTgtenc, 2, 0, 1, 1)
        self.labelAxis = QtGui.QLabel(DialogHomeSrch)
        self.labelAxis.setMinimumSize(QtCore.QSize(0, 30))
        self.labelAxis.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelAxis.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAxis.setObjectName(_fromUtf8("labelAxis"))
        self.gridLayout_2.addWidget(self.labelAxis, 1, 0, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(DialogHomeSrch)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setMinimumSize(QtCore.QSize(60, 30))
        self.graphicsView.setMaximumSize(QtCore.QSize(60, 30))
        self.graphicsView.setAcceptDrops(False)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bbClose = QtGui.QDialogButtonBox(DialogHomeSrch)
        self.bbClose.setOrientation(QtCore.Qt.Horizontal)
        self.bbClose.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.bbClose.setCenterButtons(True)
        self.bbClose.setObjectName(_fromUtf8("bbClose"))
        self.verticalLayout.addWidget(self.bbClose)

        self.retranslateUi(DialogHomeSrch)
        QtCore.QObject.connect(self.bbClose, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogHomeSrch.accept)
        QtCore.QObject.connect(self.bbClose, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogHomeSrch.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogHomeSrch)

    def retranslateUi(self, DialogHomeSrch):
        DialogHomeSrch.setWindowTitle(_translate("DialogHomeSrch", "Home and Search", None))
        self.cbHomeSearch.setItemText(0, _translate("DialogHomeSrch", "HOME", None))
        self.cbHomeSearch.setItemText(1, _translate("DialogHomeSrch", "SRCH", None))
        self.cbEdge.setItemText(0, _translate("DialogHomeSrch", "POSEDGE", None))
        self.cbEdge.setItemText(1, _translate("DialogHomeSrch", "NEGEDGE", None))
        self.cbDirection.setItemText(0, _translate("DialogHomeSrch", "-1", None))
        self.cbDirection.setItemText(1, _translate("DialogHomeSrch", "+1", None))
        self.btnGo.setText(_translate("DialogHomeSrch", "GO", None))
        self.labelEnc.setText(_translate("DialogHomeSrch", "ENC", None))
        self.labelPos.setText(_translate("DialogHomeSrch", "POS", None))
        self.labelAbsenc.setText(_translate("DialogHomeSrch", "ABSENC", None))
        self.labelInpos.setText(_translate("DialogHomeSrch", "INPOS", None))
        self.labelEncin.setText(_translate("DialogHomeSrch", "ENCIN", None))
        self.labelTgtenc.setText(_translate("DialogHomeSrch", " TGTENC ", None))
        self.labelAxis.setText(_translate("DialogHomeSrch", "AXIS", None))

