# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homing.ui'
#
# Created: Fri Feb  9 13:20:39 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_homing(object):
    def setupUi(self, homing):
        homing.setObjectName(_fromUtf8("homing"))
        homing.resize(461, 346)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(homing.sizePolicy().hasHeightForWidth())
        homing.setSizePolicy(sizePolicy)
        homing.setMinimumSize(QtCore.QSize(461, 346))
        self.gridLayout_3 = QtGui.QGridLayout(homing)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.homing_frame = QtGui.QFrame(homing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homing_frame.sizePolicy().hasHeightForWidth())
        self.homing_frame.setSizePolicy(sizePolicy)
        self.homing_frame.setMinimumSize(QtCore.QSize(182, 260))
        self.homing_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.homing_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.homing_frame.setObjectName(_fromUtf8("homing_frame"))
        self.gridLayout = QtGui.QGridLayout(self.homing_frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_9 = QtGui.QLabel(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 16))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridlayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cfgHOMESRC = QtGui.QComboBox(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMESRC.sizePolicy().hasHeightForWidth())
        self.cfgHOMESRC.setSizePolicy(sizePolicy)
        self.cfgHOMESRC.setMinimumSize(QtCore.QSize(70, 22))
        self.cfgHOMESRC.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cfgHOMESRC.setFont(font)
        self.cfgHOMESRC.setObjectName(_fromUtf8("cfgHOMESRC"))
        self.gridlayout.addWidget(self.cfgHOMESRC, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(100, 16))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridlayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.cfgHOMETYPE = QtGui.QComboBox(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMETYPE.sizePolicy().hasHeightForWidth())
        self.cfgHOMETYPE.setSizePolicy(sizePolicy)
        self.cfgHOMETYPE.setMinimumSize(QtCore.QSize(70, 22))
        self.cfgHOMETYPE.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cfgHOMETYPE.setFont(font)
        self.cfgHOMETYPE.setObjectName(_fromUtf8("cfgHOMETYPE"))
        self.gridlayout.addWidget(self.cfgHOMETYPE, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridlayout, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(370, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 16))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.homing_frame)
        self.line_2.setMinimumSize(QtCore.QSize(150, 0))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        self.cfgHOMEFLAGS = QtGui.QFrame(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS.setMinimumSize(QtCore.QSize(329, 150))
        self.cfgHOMEFLAGS.setFrameShape(QtGui.QFrame.NoFrame)
        self.cfgHOMEFLAGS.setFrameShadow(QtGui.QFrame.Plain)
        self.cfgHOMEFLAGS.setObjectName(_fromUtf8("cfgHOMEFLAGS"))
        self.verticalLayout = QtGui.QVBoxLayout(self.cfgHOMEFLAGS)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cfgHOMEFLAGS_AUTODIR = QtGui.QCheckBox(self.cfgHOMEFLAGS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS_AUTODIR.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS_AUTODIR.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS_AUTODIR.setMinimumSize(QtCore.QSize(150, 16))
        self.cfgHOMEFLAGS_AUTODIR.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEFLAGS_AUTODIR.setObjectName(_fromUtf8("cfgHOMEFLAGS_AUTODIR"))
        self.horizontalLayout.addWidget(self.cfgHOMEFLAGS_AUTODIR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cfgHOMEFLAGS_REVERSE = QtGui.QCheckBox(self.cfgHOMEFLAGS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS_REVERSE.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS_REVERSE.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS_REVERSE.setMinimumSize(QtCore.QSize(150, 16))
        self.cfgHOMEFLAGS_REVERSE.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEFLAGS_REVERSE.setObjectName(_fromUtf8("cfgHOMEFLAGS_REVERSE"))
        self.horizontalLayout_2.addWidget(self.cfgHOMEFLAGS_REVERSE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cfgHOMEFLAGS_SETPOS = QtGui.QCheckBox(self.cfgHOMEFLAGS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS_SETPOS.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS_SETPOS.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS_SETPOS.setMinimumSize(QtCore.QSize(150, 16))
        self.cfgHOMEFLAGS_SETPOS.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEFLAGS_SETPOS.setObjectName(_fromUtf8("cfgHOMEFLAGS_SETPOS"))
        self.horizontalLayout_3.addWidget(self.cfgHOMEFLAGS_SETPOS)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.cfgHOMEFLAGS_SLOW = QtGui.QCheckBox(self.cfgHOMEFLAGS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS_SLOW.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS_SLOW.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS_SLOW.setMinimumSize(QtCore.QSize(150, 16))
        self.cfgHOMEFLAGS_SLOW.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEFLAGS_SLOW.setObjectName(_fromUtf8("cfgHOMEFLAGS_SLOW"))
        self.horizontalLayout_4.addWidget(self.cfgHOMEFLAGS_SLOW)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.cfgHOMEFLAGS_NEGEDGE = QtGui.QCheckBox(self.cfgHOMEFLAGS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEFLAGS_NEGEDGE.sizePolicy().hasHeightForWidth())
        self.cfgHOMEFLAGS_NEGEDGE.setSizePolicy(sizePolicy)
        self.cfgHOMEFLAGS_NEGEDGE.setMinimumSize(QtCore.QSize(329, 22))
        self.cfgHOMEFLAGS_NEGEDGE.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEFLAGS_NEGEDGE.setObjectName(_fromUtf8("cfgHOMEFLAGS_NEGEDGE"))
        self.horizontalLayout_5.addWidget(self.cfgHOMEFLAGS_NEGEDGE)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.cfgHOMEFLAGS, 4, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(370, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.label_7 = QtGui.QLabel(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 22))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout1.addWidget(self.label_7, 0, 0, 1, 1)
        self.cfgHOMEPOS = QtGui.QSpinBox(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEPOS.sizePolicy().hasHeightForWidth())
        self.cfgHOMEPOS.setSizePolicy(sizePolicy)
        self.cfgHOMEPOS.setMinimumSize(QtCore.QSize(70, 22))
        self.cfgHOMEPOS.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cfgHOMEPOS.setFont(font)
        self.cfgHOMEPOS.setMinimum(-999999999)
        self.cfgHOMEPOS.setMaximum(999999999)
        self.cfgHOMEPOS.setObjectName(_fromUtf8("cfgHOMEPOS"))
        self.gridlayout1.addWidget(self.cfgHOMEPOS, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 22))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout1.addWidget(self.label_8, 1, 0, 1, 1)
        self.cfgHOMEVEL = QtGui.QDoubleSpinBox(self.homing_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEVEL.sizePolicy().hasHeightForWidth())
        self.cfgHOMEVEL.setSizePolicy(sizePolicy)
        self.cfgHOMEVEL.setMinimumSize(QtCore.QSize(70, 22))
        self.cfgHOMEVEL.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cfgHOMEVEL.setFont(font)
        self.cfgHOMEVEL.setMaximum(999999999.0)
        self.cfgHOMEVEL.setSingleStep(0.01)
        self.cfgHOMEVEL.setObjectName(_fromUtf8("cfgHOMEVEL"))
        self.gridlayout1.addWidget(self.cfgHOMEVEL, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridlayout1, 6, 0, 1, 1)
        self.gridLayout_3.addWidget(self.homing_frame, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 1, 0, 1, 1)

        self.retranslateUi(homing)
        QtCore.QMetaObject.connectSlotsByName(homing)

    def retranslateUi(self, homing):
        homing.setWindowTitle(_translate("homing", "Dialog", None))
        self.label_9.setText(_translate("homing", "Reference signal", None))
        self.label_10.setText(_translate("homing", "Signal type", None))
        self.label_4.setText(_translate("homing", "Flags", None))
        self.cfgHOMEFLAGS_AUTODIR.setText(_translate("homing", "auto direction", None))
        self.cfgHOMEFLAGS_REVERSE.setText(_translate("homing", "reverse search", None))
        self.cfgHOMEFLAGS_SETPOS.setText(_translate("homing", "set axis position", None))
        self.cfgHOMEFLAGS_SLOW.setText(_translate("homing", "slow search mode", None))
        self.cfgHOMEFLAGS_NEGEDGE.setText(_translate("homing", "ref pos in a falling edge when moving positive", None))
        self.label_7.setText(_translate("homing", "Home position", None))
        self.cfgHOMEPOS.setProperty("text", _translate("homing", "0", None))
        self.label_8.setText(_translate("homing", "search velocity", None))
        self.cfgHOMEVEL.setProperty("text", _translate("homing", "0.00", None))

