# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageipapdriver.ui'
#
# Created: Fri Feb  9 13:20:39 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PageiPapDriver(object):
    def setupUi(self, PageiPapDriver):
        PageiPapDriver.setObjectName(_fromUtf8("PageiPapDriver"))
        PageiPapDriver.resize(988, 613)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PageiPapDriver.sizePolicy().hasHeightForWidth())
        PageiPapDriver.setSizePolicy(sizePolicy)
        PageiPapDriver.setMinimumSize(QtCore.QSize(800, 613))
        self.gridlayout = QtGui.QGridLayout(PageiPapDriver)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.frame_right = QtGui.QFrame(PageiPapDriver)
        self.frame_right.setMinimumSize(QtCore.QSize(220, 499))
        self.frame_right.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_right.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_right.setObjectName(_fromUtf8("frame_right"))
        self.vboxlayout = QtGui.QVBoxLayout(self.frame_right)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label = QtGui.QLabel(self.frame_right)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/IcepapCfg Icons/Icepap.png")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout.addWidget(self.label)
        self.stackedWidget = QtGui.QStackedWidget(self.frame_right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(220, 353))
        self.stackedWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageTest = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTest.sizePolicy().hasHeightForWidth())
        self.pageTest.setSizePolicy(sizePolicy)
        self.pageTest.setMinimumSize(QtCore.QSize(220, 0))
        self.pageTest.setMaximumSize(QtCore.QSize(220, 16777215))
        self.pageTest.setObjectName(_fromUtf8("pageTest"))
        self.gridlayout1 = QtGui.QGridLayout(self.pageTest)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(2)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem, 1, 0, 1, 1)
        self.frame_test = QtGui.QFrame(self.pageTest)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_test.sizePolicy().hasHeightForWidth())
        self.frame_test.setSizePolicy(sizePolicy)
        self.frame_test.setMinimumSize(QtCore.QSize(220, 300))
        self.frame_test.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_test.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_test.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_test.setObjectName(_fromUtf8("frame_test"))
        self.gridlayout2 = QtGui.QGridLayout(self.frame_test)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.btnGO = QtGui.QPushButton(self.frame_test)
        self.btnGO.setMaximumSize(QtCore.QSize(24, 24))
        self.btnGO.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/small_icons/IcepapCFG Icons Petits/go-absolute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGO.setIcon(icon)
        self.btnGO.setIconSize(QtCore.QSize(22, 22))
        self.btnGO.setObjectName(_fromUtf8("btnGO"))
        self.gridlayout2.addWidget(self.btnGO, 5, 4, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_test)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frame_4)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.frame_leds = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_leds.sizePolicy().hasHeightForWidth())
        self.frame_leds.setSizePolicy(sizePolicy)
        self.frame_leds.setMinimumSize(QtCore.QSize(171, 48))
        self.frame_leds.setMaximumSize(QtCore.QSize(171, 48))
        self.frame_leds.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_leds.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_leds.setObjectName(_fromUtf8("frame_leds"))
        self.textLabel1_6_4 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_4.setGeometry(QtCore.QRect(40, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_4.setFont(font)
        self.textLabel1_6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_4.setObjectName(_fromUtf8("textLabel1_6_4"))
        self.LedLimitPos = Led(self.frame_leds)
        self.LedLimitPos.setGeometry(QtCore.QRect(137, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedLimitPos.sizePolicy().hasHeightForWidth())
        self.LedLimitPos.setSizePolicy(sizePolicy)
        self.LedLimitPos.setMinimumSize(QtCore.QSize(24, 24))
        self.LedLimitPos.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedLimitPos.setPalette(palette)
        self.LedLimitPos.setObjectName(_fromUtf8("LedLimitPos"))
        self.textLabel1_6_5 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_5.setGeometry(QtCore.QRect(8, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_5.setFont(font)
        self.textLabel1_6_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textLabel1_6_5.setObjectName(_fromUtf8("textLabel1_6_5"))
        self.LedHome = Led(self.frame_leds)
        self.LedHome.setGeometry(QtCore.QRect(72, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedHome.sizePolicy().hasHeightForWidth())
        self.LedHome.setSizePolicy(sizePolicy)
        self.LedHome.setMinimumSize(QtCore.QSize(24, 24))
        self.LedHome.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedHome.setPalette(palette)
        self.LedHome.setObjectName(_fromUtf8("LedHome"))
        self.textLabel1_6_3 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_3.setGeometry(QtCore.QRect(72, 35, 25, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_3.setFont(font)
        self.textLabel1_6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_3.setObjectName(_fromUtf8("textLabel1_6_3"))
        self.textLabel1_6 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6.setGeometry(QtCore.QRect(137, 35, 25, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6.setFont(font)
        self.textLabel1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6.setObjectName(_fromUtf8("textLabel1_6"))
        self.LedStep = Led(self.frame_leds)
        self.LedStep.setGeometry(QtCore.QRect(40, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedStep.sizePolicy().hasHeightForWidth())
        self.LedStep.setSizePolicy(sizePolicy)
        self.LedStep.setMinimumSize(QtCore.QSize(24, 24))
        self.LedStep.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedStep.setPalette(palette)
        self.LedStep.setObjectName(_fromUtf8("LedStep"))
        self.LedError = Led(self.frame_leds)
        self.LedError.setGeometry(QtCore.QRect(8, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedError.sizePolicy().hasHeightForWidth())
        self.LedError.setSizePolicy(sizePolicy)
        self.LedError.setMinimumSize(QtCore.QSize(24, 24))
        self.LedError.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 148, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedError.setPalette(palette)
        self.LedError.setObjectName(_fromUtf8("LedError"))
        self.LedLimitNeg = Led(self.frame_leds)
        self.LedLimitNeg.setGeometry(QtCore.QRect(105, 4, 24, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LedLimitNeg.sizePolicy().hasHeightForWidth())
        self.LedLimitNeg.setSizePolicy(sizePolicy)
        self.LedLimitNeg.setMinimumSize(QtCore.QSize(24, 24))
        self.LedLimitNeg.setMaximumSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LedLimitNeg.setPalette(palette)
        self.LedLimitNeg.setObjectName(_fromUtf8("LedLimitNeg"))
        self.textLabel1_6_2 = QtGui.QLabel(self.frame_leds)
        self.textLabel1_6_2.setGeometry(QtCore.QRect(105, 35, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textLabel1_6_2.setFont(font)
        self.textLabel1_6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_6_2.setObjectName(_fromUtf8("textLabel1_6_2"))
        self.hboxlayout.addWidget(self.frame_leds)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.gridlayout2.addWidget(self.frame_4, 3, 0, 1, 5)
        self.textLabel1_3_3_2 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3_3_2.setFont(font)
        self.textLabel1_3_3_2.setObjectName(_fromUtf8("textLabel1_3_3_2"))
        self.gridlayout2.addWidget(self.textLabel1_3_3_2, 1, 0, 1, 3)
        self.txtAcceleration = QtGui.QLineEdit(self.frame_test)
        self.txtAcceleration.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtAcceleration.setFont(font)
        self.txtAcceleration.setObjectName(_fromUtf8("txtAcceleration"))
        self.gridlayout2.addWidget(self.txtAcceleration, 1, 3, 1, 2)
        self.textLabel3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3.setFont(font)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.gridlayout2.addWidget(self.textLabel3, 4, 0, 1, 1)
        self.btnStopMotor = QtGui.QPushButton(self.frame_test)
        self.btnStopMotor.setMaximumSize(QtCore.QSize(24, 24))
        self.btnStopMotor.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/IcepapCfg Icons/gnome-session-halt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStopMotor.setIcon(icon1)
        self.btnStopMotor.setIconSize(QtCore.QSize(22, 22))
        self.btnStopMotor.setObjectName(_fromUtf8("btnStopMotor"))
        self.gridlayout2.addWidget(self.btnStopMotor, 6, 1, 1, 1)
        self.txtMvAbsolute = QtGui.QLineEdit(self.frame_test)
        self.txtMvAbsolute.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtMvAbsolute.setFont(font)
        self.txtMvAbsolute.setObjectName(_fromUtf8("txtMvAbsolute"))
        self.gridlayout2.addWidget(self.txtMvAbsolute, 5, 3, 1, 1)
        self.textLabel1_3_3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3_3.setFont(font)
        self.textLabel1_3_3.setObjectName(_fromUtf8("textLabel1_3_3"))
        self.gridlayout2.addWidget(self.textLabel1_3_3, 0, 0, 1, 3)
        self.frame = QtGui.QFrame(self.frame_test)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridlayout2.addWidget(self.frame, 2, 0, 1, 5)
        self.LCDPosition = QtGui.QLCDNumber(self.frame_test)
        self.LCDPosition.setMinimumSize(QtCore.QSize(0, 24))
        self.LCDPosition.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 59, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 68, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 59, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 68, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 200, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDPosition.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDPosition.setFont(font)
        self.LCDPosition.setAutoFillBackground(True)
        self.LCDPosition.setFrameShape(QtGui.QFrame.Panel)
        self.LCDPosition.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDPosition.setNumDigits(9)
        self.LCDPosition.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDPosition.setObjectName(_fromUtf8("LCDPosition"))
        self.gridlayout2.addWidget(self.LCDPosition, 4, 1, 1, 4)
        self.txtSpeed = QtGui.QLineEdit(self.frame_test)
        self.txtSpeed.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txtSpeed.setFont(font)
        self.txtSpeed.setObjectName(_fromUtf8("txtSpeed"))
        self.gridlayout2.addWidget(self.txtSpeed, 0, 3, 1, 2)
        self.btnEnable = QtGui.QPushButton(self.frame_test)
        self.btnEnable.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnable.setFont(font)
        self.btnEnable.setCheckable(True)
        self.btnEnable.setChecked(False)
        self.btnEnable.setObjectName(_fromUtf8("btnEnable"))
        self.gridlayout2.addWidget(self.btnEnable, 6, 0, 1, 1)
        self.btnGORelativePos = QtGui.QPushButton(self.frame_test)
        self.btnGORelativePos.setMaximumSize(QtCore.QSize(24, 24))
        self.btnGORelativePos.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/small_icons/IcepapCFG Icons Petits/go-relative.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGORelativePos.setIcon(icon2)
        self.btnGORelativePos.setIconSize(QtCore.QSize(22, 22))
        self.btnGORelativePos.setObjectName(_fromUtf8("btnGORelativePos"))
        self.gridlayout2.addWidget(self.btnGORelativePos, 6, 4, 1, 1)
        self.btnGORelativeNeg = QtGui.QPushButton(self.frame_test)
        self.btnGORelativeNeg.setMaximumSize(QtCore.QSize(24, 24))
        self.btnGORelativeNeg.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/small_icons/IcepapCFG Icons Petits/go-relative2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGORelativeNeg.setIcon(icon3)
        self.btnGORelativeNeg.setIconSize(QtCore.QSize(22, 22))
        self.btnGORelativeNeg.setObjectName(_fromUtf8("btnGORelativeNeg"))
        self.gridlayout2.addWidget(self.btnGORelativeNeg, 6, 2, 1, 1)
        self.textLabel1_3 = QtGui.QLabel(self.frame_test)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel1_3.setFont(font)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.gridlayout2.addWidget(self.textLabel1_3, 5, 0, 1, 3)
        self.txtGORelative = QtGui.QLineEdit(self.frame_test)
        self.txtGORelative.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtGORelative.setFont(font)
        self.txtGORelative.setObjectName(_fromUtf8("txtGORelative"))
        self.gridlayout2.addWidget(self.txtGORelative, 6, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame_test)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout1.setSpacing(2)
        self.hboxlayout1.setMargin(2)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.sliderJog = QtGui.QSlider(self.groupBox)
        self.sliderJog.setMouseTracking(False)
        self.sliderJog.setMinimum(-4)
        self.sliderJog.setMaximum(4)
        self.sliderJog.setPageStep(1)
        self.sliderJog.setProperty("value", 0)
        self.sliderJog.setSliderPosition(0)
        self.sliderJog.setOrientation(QtCore.Qt.Horizontal)
        self.sliderJog.setInvertedAppearance(False)
        self.sliderJog.setInvertedControls(False)
        self.sliderJog.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderJog.setTickInterval(2)
        self.sliderJog.setObjectName(_fromUtf8("sliderJog"))
        self.hboxlayout1.addWidget(self.sliderJog)
        self.gridlayout2.addWidget(self.groupBox, 7, 0, 1, 5)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.cmdCSWITCH = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.cmdCSWITCH.sizePolicy().hasHeightForWidth())
        self.cmdCSWITCH.setSizePolicy(sizePolicy)
        self.cmdCSWITCH.setObjectName(_fromUtf8("cmdCSWITCH"))
        self.cmdCSWITCH.addItem(_fromUtf8(""))
        self.cmdCSWITCH.addItem(_fromUtf8(""))
        self.cmdCSWITCH.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmdCSWITCH)
        self.gridlayout2.addWidget(self.groupBox_2, 8, 0, 1, 5)
        self.gridlayout1.addWidget(self.frame_test, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTest)
        self.pageHistoric = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageHistoric.sizePolicy().hasHeightForWidth())
        self.pageHistoric.setSizePolicy(sizePolicy)
        self.pageHistoric.setMinimumSize(QtCore.QSize(220, 0))
        self.pageHistoric.setMaximumSize(QtCore.QSize(220, 420))
        self.pageHistoric.setObjectName(_fromUtf8("pageHistoric"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.pageHistoric)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.historicWidget = HistoricCfgWidget(self.pageHistoric)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historicWidget.sizePolicy().hasHeightForWidth())
        self.historicWidget.setSizePolicy(sizePolicy)
        self.historicWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.historicWidget.setMaximumSize(QtCore.QSize(220, 420))
        self.historicWidget.setObjectName(_fromUtf8("historicWidget"))
        self.hboxlayout2.addWidget(self.historicWidget)
        self.stackedWidget.addWidget(self.pageHistoric)
        self.vboxlayout.addWidget(self.stackedWidget)
        self.btnSendCfg = QtGui.QPushButton(self.frame_right)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/small_icons/IcepapCfg Icons/Icepapicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSendCfg.setIcon(icon4)
        self.btnSendCfg.setIconSize(QtCore.QSize(20, 20))
        self.btnSendCfg.setObjectName(_fromUtf8("btnSendCfg"))
        self.vboxlayout.addWidget(self.btnSendCfg)
        self.btnSaveCfg = QtGui.QPushButton(self.frame_right)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/IcepapCfg Icons/sign.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveCfg.setIcon(icon5)
        self.btnSaveCfg.setIconSize(QtCore.QSize(20, 20))
        self.btnSaveCfg.setObjectName(_fromUtf8("btnSaveCfg"))
        self.vboxlayout.addWidget(self.btnSaveCfg)
        self.btnUndo = QtGui.QPushButton(self.frame_right)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/small_icons/IcepapCFG Icons Petits/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUndo.setIcon(icon6)
        self.btnUndo.setIconSize(QtCore.QSize(20, 20))
        self.btnUndo.setObjectName(_fromUtf8("btnUndo"))
        self.vboxlayout.addWidget(self.btnUndo)
        self.btnRestore = QtGui.QPushButton(self.frame_right)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/IcepapCfg Icons/update-manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRestore.setIcon(icon7)
        self.btnRestore.setIconSize(QtCore.QSize(20, 20))
        self.btnRestore.setObjectName(_fromUtf8("btnRestore"))
        self.vboxlayout.addWidget(self.btnRestore)
        self.gridlayout.addWidget(self.frame_right, 0, 1, 2, 1)
        self.frame_description = QtGui.QFrame(PageiPapDriver)
        self.frame_description.setMinimumSize(QtCore.QSize(16, 50))
        self.frame_description.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frame_description.setAutoFillBackground(True)
        self.frame_description.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_description.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_description.setObjectName(_fromUtf8("frame_description"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.frame_description)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.label_2 = QtGui.QLabel(self.frame_description)
        self.label_2.setMaximumSize(QtCore.QSize(31, 26))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout4.addWidget(self.label_2)
        self.dscDriverName = QtGui.QLabel(self.frame_description)
        self.dscDriverName.setMaximumSize(QtCore.QSize(16777215, 26))
        self.dscDriverName.setObjectName(_fromUtf8("dscDriverName"))
        self.hboxlayout4.addWidget(self.dscDriverName)
        self.hboxlayout3.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        self.label_4 = QtGui.QLabel(self.frame_description)
        self.label_4.setMaximumSize(QtCore.QSize(41, 26))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hboxlayout5.addWidget(self.label_4)
        self.dscActive = QtGui.QLabel(self.frame_description)
        self.dscActive.setObjectName(_fromUtf8("dscActive"))
        self.hboxlayout5.addWidget(self.dscActive)
        self.hboxlayout3.addLayout(self.hboxlayout5)
        self.btnBlink = QtGui.QPushButton(self.frame_description)
        self.btnBlink.setCheckable(True)
        self.btnBlink.setObjectName(_fromUtf8("btnBlink"))
        self.hboxlayout3.addWidget(self.btnBlink)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName(_fromUtf8("hboxlayout6"))
        self.label_3 = QtGui.QLabel(self.frame_description)
        self.label_3.setMaximumSize(QtCore.QSize(63, 26))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.hboxlayout6.addWidget(self.label_3)
        self.dscSignature = QtGui.QLabel(self.frame_description)
        self.dscSignature.setObjectName(_fromUtf8("dscSignature"))
        self.hboxlayout6.addWidget(self.dscSignature)
        self.hboxlayout3.addLayout(self.hboxlayout6)
        self.gridlayout.addWidget(self.frame_description, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(PageiPapDriver)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_TuneAndTesting = QtGui.QWidget()
        self.tab_TuneAndTesting.setObjectName(_fromUtf8("tab_TuneAndTesting"))
        self.gridlayout3 = QtGui.QGridLayout(self.tab_TuneAndTesting)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.btnStatus = QtGui.QPushButton(self.tab_TuneAndTesting)
        self.btnStatus.setObjectName(_fromUtf8("btnStatus"))
        self.gridlayout3.addWidget(self.btnStatus, 6, 6, 1, 1)
        self.cmdAUXPS = QtGui.QCheckBox(self.tab_TuneAndTesting)
        self.cmdAUXPS.setObjectName(_fromUtf8("cmdAUXPS"))
        self.gridlayout3.addWidget(self.cmdAUXPS, 0, 1, 1, 1)
        self.groupBox_21 = QtGui.QGroupBox(self.tab_TuneAndTesting)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.cbHomeSrch1 = QtGui.QComboBox(self.groupBox_21)
        self.cbHomeSrch1.setGeometry(QtCore.QRect(10, 20, 51, 31))
        self.cbHomeSrch1.setObjectName(_fromUtf8("cbHomeSrch1"))
        self.cbHomeSrch1.addItem(_fromUtf8(""))
        self.cbHomeSrch1.addItem(_fromUtf8(""))
        self.cbHomeSrch2 = QtGui.QComboBox(self.groupBox_21)
        self.cbHomeSrch2.setGeometry(QtCore.QRect(60, 20, 51, 30))
        self.cbHomeSrch2.setObjectName(_fromUtf8("cbHomeSrch2"))
        self.cbHomeSrch2.addItem(_fromUtf8(""))
        self.cbHomeSrch2.addItem(_fromUtf8(""))
        self.cbHomeSrch2.addItem(_fromUtf8(""))
        self.cbHomeSrch3 = QtGui.QComboBox(self.groupBox_21)
        self.cbHomeSrch3.setEnabled(False)
        self.cbHomeSrch3.setGeometry(QtCore.QRect(110, 20, 51, 30))
        self.cbHomeSrch3.setObjectName(_fromUtf8("cbHomeSrch3"))
        self.cbHomeSrch3.addItem(_fromUtf8(""))
        self.cbHomeSrch3.addItem(_fromUtf8(""))
        self.btnHomeSrchGo = QtGui.QPushButton(self.groupBox_21)
        self.btnHomeSrchGo.setGeometry(QtCore.QRect(10, 50, 41, 31))
        self.btnHomeSrchGo.setObjectName(_fromUtf8("btnHomeSrchGo"))
        self.cbHomeSrch4 = QtGui.QComboBox(self.groupBox_21)
        self.cbHomeSrch4.setEnabled(False)
        self.cbHomeSrch4.setGeometry(QtCore.QRect(160, 20, 51, 30))
        self.cbHomeSrch4.setObjectName(_fromUtf8("cbHomeSrch4"))
        self.cbHomeSrch4.addItem(_fromUtf8(""))
        self.cbHomeSrch4.addItem(_fromUtf8(""))
        self.homeBrowser = QtGui.QTextBrowser(self.groupBox_21)
        self.homeBrowser.setGeometry(QtCore.QRect(60, 50, 151, 111))
        self.homeBrowser.setObjectName(_fromUtf8("homeBrowser"))
        self.btnHomeStat = QtGui.QPushButton(self.groupBox_21)
        self.btnHomeStat.setGeometry(QtCore.QRect(10, 80, 41, 28))
        self.btnHomeStat.setToolTip(_fromUtf8(""))
        self.btnHomeStat.setObjectName(_fromUtf8("btnHomeStat"))
        self.gridlayout3.addWidget(self.groupBox_21, 3, 1, 3, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setMargin(2)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.LCDPositionTest = QtGui.QLCDNumber(self.tab_TuneAndTesting)
        self.LCDPositionTest.setMinimumSize(QtCore.QSize(0, 40))
        self.LCDPositionTest.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDPositionTest.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDPositionTest.setFont(font)
        self.LCDPositionTest.setAutoFillBackground(True)
        self.LCDPositionTest.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDPositionTest.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDPositionTest.setNumDigits(14)
        self.LCDPositionTest.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDPositionTest.setObjectName(_fromUtf8("LCDPositionTest"))
        self.gridlayout4.addWidget(self.LCDPositionTest, 2, 1, 1, 4)
        self.btnSetPos = QtGui.QPushButton(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetPos.sizePolicy().hasHeightForWidth())
        self.btnSetPos.setSizePolicy(sizePolicy)
        self.btnSetPos.setMinimumSize(QtCore.QSize(30, 0))
        self.btnSetPos.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnSetPos.setObjectName(_fromUtf8("btnSetPos"))
        self.gridlayout4.addWidget(self.btnSetPos, 1, 1, 1, 1)
        self.textLabel3_6 = QtGui.QLabel(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_6.setFont(font)
        self.textLabel3_6.setObjectName(_fromUtf8("textLabel3_6"))
        self.gridlayout4.addWidget(self.textLabel3_6, 0, 0, 1, 2)
        self.cb_pos_sel = QtGui.QComboBox(self.tab_TuneAndTesting)
        self.cb_pos_sel.setObjectName(_fromUtf8("cb_pos_sel"))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.cb_pos_sel.addItem(_fromUtf8(""))
        self.gridlayout4.addWidget(self.cb_pos_sel, 0, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem4, 0, 3, 1, 1)
        self.txtPos = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtPos.setObjectName(_fromUtf8("txtPos"))
        self.gridlayout4.addWidget(self.txtPos, 1, 4, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout4)
        self.line_2 = QtGui.QFrame(self.tab_TuneAndTesting)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.vboxlayout1.addWidget(self.line_2)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setMargin(2)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        self.chkEctsTurn = QtGui.QCheckBox(self.tab_TuneAndTesting)
        self.chkEctsTurn.setObjectName(_fromUtf8("chkEctsTurn"))
        self.gridlayout5.addWidget(self.chkEctsTurn, 1, 1, 1, 1)
        self.LCDEncoder = QtGui.QLCDNumber(self.tab_TuneAndTesting)
        self.LCDEncoder.setMinimumSize(QtCore.QSize(0, 40))
        self.LCDEncoder.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.LCDEncoder.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LCDEncoder.setFont(font)
        self.LCDEncoder.setAutoFillBackground(True)
        self.LCDEncoder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDEncoder.setFrameShadow(QtGui.QFrame.Raised)
        self.LCDEncoder.setNumDigits(14)
        self.LCDEncoder.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCDEncoder.setObjectName(_fromUtf8("LCDEncoder"))
        self.gridlayout5.addWidget(self.LCDEncoder, 6, 1, 1, 4)
        self.txtEctsTurn = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtEctsTurn.setReadOnly(True)
        self.txtEctsTurn.setObjectName(_fromUtf8("txtEctsTurn"))
        self.gridlayout5.addWidget(self.txtEctsTurn, 1, 2, 1, 1)
        self.textLabel3_5 = QtGui.QLabel(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_5.setFont(font)
        self.textLabel3_5.setObjectName(_fromUtf8("textLabel3_5"))
        self.gridlayout5.addWidget(self.textLabel3_5, 0, 0, 1, 2)
        self.cb_enc_sel = QtGui.QComboBox(self.tab_TuneAndTesting)
        self.cb_enc_sel.setObjectName(_fromUtf8("cb_enc_sel"))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.cb_enc_sel.addItem(_fromUtf8(""))
        self.gridlayout5.addWidget(self.cb_enc_sel, 0, 4, 1, 1)
        self.btnSetEnc = QtGui.QPushButton(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetEnc.sizePolicy().hasHeightForWidth())
        self.btnSetEnc.setSizePolicy(sizePolicy)
        self.btnSetEnc.setMinimumSize(QtCore.QSize(30, 0))
        self.btnSetEnc.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnSetEnc.setObjectName(_fromUtf8("btnSetEnc"))
        self.gridlayout5.addWidget(self.btnSetEnc, 1, 3, 1, 1)
        self.txtEnc = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtEnc.setObjectName(_fromUtf8("txtEnc"))
        self.gridlayout5.addWidget(self.txtEnc, 1, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem5, 0, 2, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout5)
        self.gridlayout3.addLayout(self.vboxlayout1, 0, 2, 6, 8)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_TuneAndTesting)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_54 = QtGui.QLabel(self.groupBox_13)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout.addWidget(self.label_54, 1, 0, 1, 1)
        self.cmdINFOCPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOCPOL.setObjectName(_fromUtf8("cmdINFOCPOL"))
        self.gridLayout.addWidget(self.cmdINFOCPOL, 3, 2, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_13)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout.addWidget(self.label_53, 2, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout.addWidget(self.label_56, 0, 2, 1, 1)
        self.cmdINFOASRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOASRC.setObjectName(_fromUtf8("cmdINFOASRC"))
        self.gridLayout.addWidget(self.cmdINFOASRC, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_13)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 3, 0, 1, 1)
        self.cmdINFOBPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOBPOL.setObjectName(_fromUtf8("cmdINFOBPOL"))
        self.gridLayout.addWidget(self.cmdINFOBPOL, 2, 2, 1, 1)
        self.cmdINFOBSRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOBSRC.setObjectName(_fromUtf8("cmdINFOBSRC"))
        self.gridLayout.addWidget(self.cmdINFOBSRC, 2, 1, 1, 1)
        self.cmdINFOAPOL = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOAPOL.setObjectName(_fromUtf8("cmdINFOAPOL"))
        self.gridLayout.addWidget(self.cmdINFOAPOL, 1, 2, 1, 1)
        self.cmdINFOCSRC = QtGui.QComboBox(self.groupBox_13)
        self.cmdINFOCSRC.setObjectName(_fromUtf8("cmdINFOCSRC"))
        self.gridLayout.addWidget(self.cmdINFOCSRC, 3, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setTextFormat(QtCore.Qt.PlainText)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout.addWidget(self.label_55, 0, 1, 1, 1)
        self.gridlayout3.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_TuneAndTesting)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.cmdINDEXER = QtGui.QComboBox(self.groupBox_3)
        self.cmdINDEXER.setGeometry(QtCore.QRect(0, 20, 192, 25))
        self.cmdINDEXER.setObjectName(_fromUtf8("cmdINDEXER"))
        self.gridlayout3.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.txtEpu = QtGui.QLineEdit(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEpu.sizePolicy().hasHeightForWidth())
        self.txtEpu.setSizePolicy(sizePolicy)
        self.txtEpu.setObjectName(_fromUtf8("txtEpu"))
        self.gridlayout3.addWidget(self.txtEpu, 6, 4, 1, 1)
        self.btnCurves = QtGui.QPushButton(self.tab_TuneAndTesting)
        self.btnCurves.setObjectName(_fromUtf8("btnCurves"))
        self.gridlayout3.addWidget(self.btnCurves, 6, 7, 1, 1)
        self.txtSpu = QtGui.QLineEdit(self.tab_TuneAndTesting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSpu.sizePolicy().hasHeightForWidth())
        self.txtSpu.setSizePolicy(sizePolicy)
        self.txtSpu.setObjectName(_fromUtf8("txtSpu"))
        self.gridlayout3.addWidget(self.txtSpu, 6, 2, 1, 1)
        self.txtOffset = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtOffset.setObjectName(_fromUtf8("txtOffset"))
        self.gridlayout3.addWidget(self.txtOffset, 6, 5, 1, 1)
        self.txtPosition = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtPosition.setReadOnly(True)
        self.txtPosition.setObjectName(_fromUtf8("txtPosition"))
        self.gridlayout3.addWidget(self.txtPosition, 8, 2, 1, 3)
        self.txtEncoder = QtGui.QLineEdit(self.tab_TuneAndTesting)
        self.txtEncoder.setReadOnly(True)
        self.txtEncoder.setObjectName(_fromUtf8("txtEncoder"))
        self.gridlayout3.addWidget(self.txtEncoder, 8, 5, 1, 5)
        self.tabWidget.addTab(self.tab_TuneAndTesting, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(PageiPapDriver)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.cb_enc_sel.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(PageiPapDriver)

    def retranslateUi(self, PageiPapDriver):
        PageiPapDriver.setWindowTitle(_translate("PageiPapDriver", "Form", None))
        self.textLabel1_6_4.setText(_translate("PageiPapDriver", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:7pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Step</p></body></html>", None))
        self.textLabel1_6_5.setText(_translate("PageiPapDriver", "Stat", None))
        self.textLabel1_6_3.setText(_translate("PageiPapDriver", "Home", None))
        self.textLabel1_6.setText(_translate("PageiPapDriver", "Limit+", None))
        self.textLabel1_6_2.setText(_translate("PageiPapDriver", "Limit-", None))
        self.textLabel1_3_3_2.setText(_translate("PageiPapDriver", "Acc. time (sec)", None))
        self.textLabel3.setText(_translate("PageiPapDriver", "Position", None))
        self.textLabel1_3_3.setText(_translate("PageiPapDriver", "Speed (steps/sec)", None))
        self.btnEnable.setText(_translate("PageiPapDriver", "ON", None))
        self.textLabel1_3.setText(_translate("PageiPapDriver", "Move absolute", None))
        self.groupBox.setTitle(_translate("PageiPapDriver", "Jog", None))
        self.groupBox_2.setTitle(_translate("PageiPapDriver", "Limit Switches setup", None))
        self.label_5.setText(_translate("PageiPapDriver", "Cswitch mode", None))
        self.cmdCSWITCH.setItemText(0, _translate("PageiPapDriver", "NORMAL", None))
        self.cmdCSWITCH.setItemText(1, _translate("PageiPapDriver", "SMART", None))
        self.cmdCSWITCH.setItemText(2, _translate("PageiPapDriver", "STICKY", None))
        self.btnSendCfg.setText(_translate("PageiPapDriver", "Send Config to board", None))
        self.btnSaveCfg.setText(_translate("PageiPapDriver", "Validate Config", None))
        self.btnUndo.setText(_translate("PageiPapDriver", "Discard changes", None))
        self.btnRestore.setText(_translate("PageiPapDriver", "Reload board config", None))
        self.label_2.setText(_translate("PageiPapDriver", "Axis:", None))
        self.dscDriverName.setText(_translate("PageiPapDriver", "<DRIVER_NAME>", None))
        self.label_4.setText(_translate("PageiPapDriver", "Active:", None))
        self.dscActive.setText(_translate("PageiPapDriver", "<YES/NO>", None))
        self.btnBlink.setText(_translate("PageiPapDriver", "blink driver", None))
        self.label_3.setText(_translate("PageiPapDriver", "Last config:", None))
        self.dscSignature.setText(_translate("PageiPapDriver", "<_DATE_>", None))
        self.btnStatus.setText(_translate("PageiPapDriver", "Status", None))
        self.cmdAUXPS.setText(_translate("PageiPapDriver", "Aux Supply 5V", None))
        self.groupBox_21.setTitle(_translate("PageiPapDriver", "HOME/SRCH", None))
        self.cbHomeSrch1.setItemText(0, _translate("PageiPapDriver", "HOME", None))
        self.cbHomeSrch1.setItemText(1, _translate("PageiPapDriver", "SRCH", None))
        self.cbHomeSrch2.setItemText(0, _translate("PageiPapDriver", "+1", None))
        self.cbHomeSrch2.setItemText(1, _translate("PageiPapDriver", "0", None))
        self.cbHomeSrch2.setItemText(2, _translate("PageiPapDriver", "-1", None))
        self.cbHomeSrch3.setItemText(0, _translate("PageiPapDriver", "POSEDGE", None))
        self.cbHomeSrch3.setItemText(1, _translate("PageiPapDriver", "NEGEDGE", None))
        self.btnHomeSrchGo.setText(_translate("PageiPapDriver", "Go", None))
        self.cbHomeSrch4.setItemText(0, _translate("PageiPapDriver", "+1", None))
        self.cbHomeSrch4.setItemText(1, _translate("PageiPapDriver", "-1", None))
        self.btnHomeStat.setText(_translate("PageiPapDriver", "Update", None))
        self.btnSetPos.setText(_translate("PageiPapDriver", "Set", None))
        self.textLabel3_6.setText(_translate("PageiPapDriver", "Position", None))
        self.cb_pos_sel.setItemText(0, _translate("PageiPapDriver", "Axis", None))
        self.cb_pos_sel.setItemText(1, _translate("PageiPapDriver", "Indexer", None))
        self.cb_pos_sel.setItemText(2, _translate("PageiPapDriver", "ExtErr", None))
        self.cb_pos_sel.setItemText(3, _translate("PageiPapDriver", "ShftEnc", None))
        self.cb_pos_sel.setItemText(4, _translate("PageiPapDriver", "TgtEnc", None))
        self.cb_pos_sel.setItemText(5, _translate("PageiPapDriver", "EncIn", None))
        self.cb_pos_sel.setItemText(6, _translate("PageiPapDriver", "InPos", None))
        self.cb_pos_sel.setItemText(7, _translate("PageiPapDriver", "AbsEnc", None))
        self.chkEctsTurn.setText(_translate("PageiPapDriver", "Ects/turn", None))
        self.textLabel3_5.setText(_translate("PageiPapDriver", "Encoder", None))
        self.cb_enc_sel.setItemText(0, _translate("PageiPapDriver", "Axis", None))
        self.cb_enc_sel.setItemText(1, _translate("PageiPapDriver", "Indexer", None))
        self.cb_enc_sel.setItemText(2, _translate("PageiPapDriver", "ExtErr", None))
        self.cb_enc_sel.setItemText(3, _translate("PageiPapDriver", "ShftEnc", None))
        self.cb_enc_sel.setItemText(4, _translate("PageiPapDriver", "TgtEnc", None))
        self.cb_enc_sel.setItemText(5, _translate("PageiPapDriver", "EncIn", None))
        self.cb_enc_sel.setItemText(6, _translate("PageiPapDriver", "InPos", None))
        self.cb_enc_sel.setItemText(7, _translate("PageiPapDriver", "AbsEnc", None))
        self.btnSetEnc.setText(_translate("PageiPapDriver", "Set", None))
        self.groupBox_13.setTitle(_translate("PageiPapDriver", "Info Signals", None))
        self.label_54.setText(_translate("PageiPapDriver", "InfoA", None))
        self.label_53.setText(_translate("PageiPapDriver", "InfoB", None))
        self.label_56.setText(_translate("PageiPapDriver", "Polarity", None))
        self.label_52.setText(_translate("PageiPapDriver", "InfoC", None))
        self.label_55.setText(_translate("PageiPapDriver", "Source", None))
        self.groupBox_3.setTitle(_translate("PageiPapDriver", "Indexer", None))
        self.btnCurves.setText(_translate("PageiPapDriver", "Curves", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_TuneAndTesting), _translate("PageiPapDriver", "Tune and testing", None))

from Led import Led
from historiccfgwidget import HistoricCfgWidget
import icepapcms_rc
