#!/usr/bin/python

import sys, os
from ui_icepapcms import IcepapCMS, IcepapApp
from PyQt4 import QtCore, QtGui
from lib_icepapcms import *


if __name__ == "__main__":
    sys.argv[0] =  os.path.realpath(sys.argv[0])
    pathname = os.path.dirname(sys.argv[0])
    app = IcepapApp(sys.argv)   
