#!/usr/bin/python

import sys, os
from ui_icepapcms import ipapconsole
from PyQt4 import QtGui

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    console = ipapconsole.IcepapConsole(None)
    console.show()
    sys.exit(app.exec_())
