# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'axis.ui'
#
# Created: Tue Aug  4 15:08:47 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_axis(object):
    def setupUi(self, axis):
        axis.setObjectName("axis")
        axis.resize(512, 487)
        axis.setMinimumSize(QtCore.QSize(410, 470))
        axis.setSizeIncrement(QtCore.QSize(1, 1))
        self.gridlayout = QtGui.QGridLayout(axis)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.axis_frame = QtGui.QFrame(axis)
        self.axis_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.axis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.axis_frame.setObjectName("axis_frame")
        self.gridlayout1 = QtGui.QGridLayout(self.axis_frame)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(0)
        self.gridlayout1.setObjectName("gridlayout1")
        self.frame = QtGui.QFrame(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(192, 300))
        self.frame.setSizeIncrement(QtCore.QSize(30, 30))
        self.frame.setBaseSize(QtCore.QSize(192, 197))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridlayout2 = QtGui.QGridLayout(self.frame)
        self.gridlayout2.setMargin(5)
        self.gridlayout2.setHorizontalSpacing(0)
        self.gridlayout2.setVerticalSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.cfgACTIVE = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgACTIVE.sizePolicy().hasHeightForWidth())
        self.cfgACTIVE.setSizePolicy(sizePolicy)
        self.cfgACTIVE.setMinimumSize(QtCore.QSize(60, 16))
        self.cfgACTIVE.setBaseSize(QtCore.QSize(66, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cfgACTIVE.setFont(font)
        self.cfgACTIVE.setObjectName("cfgACTIVE")
        self.hboxlayout.addWidget(self.cfgACTIVE)
        spacerItem = QtGui.QSpacerItem(40, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(45, 16))
        self.label.setBaseSize(QtCore.QSize(39, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.cfgPROTLEVEL = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgPROTLEVEL.sizePolicy().hasHeightForWidth())
        self.cfgPROTLEVEL.setSizePolicy(sizePolicy)
        self.cfgPROTLEVEL.setMinimumSize(QtCore.QSize(50, 16))
        self.cfgPROTLEVEL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgPROTLEVEL.setMouseTracking(False)
        self.cfgPROTLEVEL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cfgPROTLEVEL.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cfgPROTLEVEL.setAutoFillBackground(False)
        self.cfgPROTLEVEL.setMaximum(999999999)
        self.cfgPROTLEVEL.setProperty("editable", QtCore.QVariant(True))
        self.cfgPROTLEVEL.setObjectName("cfgPROTLEVEL")
        self.hboxlayout.addWidget(self.cfgPROTLEVEL)
        self.gridlayout2.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(25, 16))
        self.label_2.setBaseSize(QtCore.QSize(39, 16))
        self.label_2.setObjectName("label_2")
        self.hboxlayout1.addWidget(self.label_2)
        self.txtDriverName = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDriverName.sizePolicy().hasHeightForWidth())
        self.txtDriverName.setSizePolicy(sizePolicy)
        self.txtDriverName.setMinimumSize(QtCore.QSize(75, 16))
        self.txtDriverName.setMaximumSize(QtCore.QSize(16777215, 22))
        self.txtDriverName.setBaseSize(QtCore.QSize(100, 20))
        self.txtDriverName.setObjectName("txtDriverName")
        self.hboxlayout1.addWidget(self.txtDriverName)
        self.cfgNAMELOCK = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgNAMELOCK.sizePolicy().hasHeightForWidth())
        self.cfgNAMELOCK.setSizePolicy(sizePolicy)
        self.cfgNAMELOCK.setMinimumSize(QtCore.QSize(65, 16))
        self.cfgNAMELOCK.setBaseSize(QtCore.QSize(66, 18))
        self.cfgNAMELOCK.setObjectName("cfgNAMELOCK")
        self.hboxlayout1.addWidget(self.cfgNAMELOCK)
        self.gridlayout2.addLayout(self.hboxlayout1, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(186, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridlayout2.addItem(spacerItem1, 2, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setContentsMargins(-1, -1, -1, 1)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(44, 16))
        self.label_3.setBaseSize(QtCore.QSize(39, 16))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.hboxlayout3.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(5, 50))
        self.line.setBaseSize(QtCore.QSize(10, 61))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout3.addWidget(self.line)
        self.hboxlayout2.addLayout(self.hboxlayout3)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setContentsMargins(-1, 0, -1, 0)
        self.gridlayout3.setObjectName("gridlayout3")
        self.cfgANSTEP = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgANSTEP.sizePolicy().hasHeightForWidth())
        self.cfgANSTEP.setSizePolicy(sizePolicy)
        self.cfgANSTEP.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgANSTEP.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgANSTEP.setBaseSize(QtCore.QSize(80, 16))
        self.cfgANSTEP.setWrapping(False)
        self.cfgANSTEP.setMaximum(999999999)
        self.cfgANSTEP.setObjectName("cfgANSTEP")
        self.gridlayout3.addWidget(self.cfgANSTEP, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(35, 16))
        self.label_4.setBaseSize(QtCore.QSize(39, 16))
        self.label_4.setObjectName("label_4")
        self.gridlayout3.addWidget(self.label_4, 0, 1, 1, 1)
        self.cfgANTURN = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgANTURN.sizePolicy().hasHeightForWidth())
        self.cfgANTURN.setSizePolicy(sizePolicy)
        self.cfgANTURN.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgANTURN.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgANTURN.setBaseSize(QtCore.QSize(80, 16))
        self.cfgANTURN.setMaximum(999999999)
        self.cfgANTURN.setObjectName("cfgANTURN")
        self.gridlayout3.addWidget(self.cfgANTURN, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(30, 16))
        self.label_5.setBaseSize(QtCore.QSize(39, 16))
        self.label_5.setObjectName("label_5")
        self.gridlayout3.addWidget(self.label_5, 1, 1, 1, 1)
        self.hboxlayout2.addLayout(self.gridlayout3)
        self.gridlayout2.addLayout(self.hboxlayout2, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(186, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridlayout2.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.label_6 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(70, 16))
        self.label_6.setBaseSize(QtCore.QSize(50, 16))
        self.label_6.setObjectName("label_6")
        self.gridlayout4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(70, 16))
        self.label_7.setBaseSize(QtCore.QSize(50, 16))
        self.label_7.setObjectName("label_7")
        self.gridlayout4.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(130, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(130, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem4, 0, 2, 1, 1)
        self.cfgPOSSRC = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgPOSSRC.sizePolicy().hasHeightForWidth())
        self.cfgPOSSRC.setSizePolicy(sizePolicy)
        self.cfgPOSSRC.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgPOSSRC.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgPOSSRC.setObjectName("cfgPOSSRC")
        self.gridlayout4.addWidget(self.cfgPOSSRC, 0, 1, 1, 1)
        self.cfgINDEXER = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgINDEXER.sizePolicy().hasHeightForWidth())
        self.cfgINDEXER.setSizePolicy(sizePolicy)
        self.cfgINDEXER.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgINDEXER.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgINDEXER.setObjectName("cfgINDEXER")
        self.gridlayout4.addWidget(self.cfgINDEXER, 1, 1, 1, 1)
        self.gridlayout2.addLayout(self.gridlayout4, 5, 0, 1, 1)
        self.gridlayout1.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(178, 174))
        self.frame_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.frame_2.setBaseSize(QtCore.QSize(178, 174))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.vboxlayout = QtGui.QVBoxLayout(self.frame_2)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setContentsMargins(5, 5, 10, 5)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label_10 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 16))
        self.label_10.setBaseSize(QtCore.QSize(50, 16))
        self.label_10.setObjectName("label_10")
        self.hboxlayout4.addWidget(self.label_10)
        self.txtMotorType = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMotorType.sizePolicy().hasHeightForWidth())
        self.txtMotorType.setSizePolicy(sizePolicy)
        self.txtMotorType.setMinimumSize(QtCore.QSize(100, 16))
        self.txtMotorType.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtMotorType.setBaseSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtMotorType.setFont(font)
        self.txtMotorType.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtMotorType.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtMotorType.setTextFormat(QtCore.Qt.PlainText)
        self.txtMotorType.setScaledContents(True)
        self.txtMotorType.setObjectName("txtMotorType")
        self.hboxlayout4.addWidget(self.txtMotorType)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setSpacing(10)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label_11 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(70, 16))
        self.label_11.setBaseSize(QtCore.QSize(50, 16))
        self.label_11.setObjectName("label_11")
        self.hboxlayout5.addWidget(self.label_11)
        self.txtNCURR = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNCURR.sizePolicy().hasHeightForWidth())
        self.txtNCURR.setSizePolicy(sizePolicy)
        self.txtNCURR.setMinimumSize(QtCore.QSize(30, 16))
        self.txtNCURR.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtNCURR.setBaseSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtNCURR.setFont(font)
        self.txtNCURR.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtNCURR.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtNCURR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtNCURR.setObjectName("txtNCURR")
        self.hboxlayout5.addWidget(self.txtNCURR)
        self.label_12 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(40, 16))
        self.label_12.setBaseSize(QtCore.QSize(40, 16))
        self.label_12.setObjectName("label_12")
        self.hboxlayout5.addWidget(self.label_12)
        self.vboxlayout.addLayout(self.hboxlayout5)
        self.cfgPOWERON = QtGui.QCheckBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgPOWERON.sizePolicy().hasHeightForWidth())
        self.cfgPOWERON.setSizePolicy(sizePolicy)
        self.cfgPOWERON.setMinimumSize(QtCore.QSize(160, 16))
        self.cfgPOWERON.setBaseSize(QtCore.QSize(220, 18))
        self.cfgPOWERON.setObjectName("cfgPOWERON")
        self.vboxlayout.addWidget(self.cfgPOWERON)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_13 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(70, 16))
        self.label_13.setBaseSize(QtCore.QSize(100, 16))
        self.label_13.setObjectName("label_13")
        self.hboxlayout6.addWidget(self.label_13)
        self.cfgMOTSENSE = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgMOTSENSE.sizePolicy().hasHeightForWidth())
        self.cfgMOTSENSE.setSizePolicy(sizePolicy)
        self.cfgMOTSENSE.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgMOTSENSE.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgMOTSENSE.setBaseSize(QtCore.QSize(80, 16))
        self.cfgMOTSENSE.setObjectName("cfgMOTSENSE")
        self.hboxlayout6.addWidget(self.cfgMOTSENSE)
        self.vboxlayout.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_14 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(30, 16))
        self.label_14.setBaseSize(QtCore.QSize(40, 16))
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.hboxlayout7.addWidget(self.label_14)
        self.line_2 = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hboxlayout7.addWidget(self.line_2)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")
        self.label_15 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(30, 16))
        self.label_15.setBaseSize(QtCore.QSize(40, 16))
        self.label_15.setObjectName("label_15")
        self.gridlayout5.addWidget(self.label_15, 0, 0, 1, 1)
        self.cfgLPPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgLPPOL.sizePolicy().hasHeightForWidth())
        self.cfgLPPOL.setSizePolicy(sizePolicy)
        self.cfgLPPOL.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgLPPOL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgLPPOL.setObjectName("cfgLPPOL")
        self.gridlayout5.addWidget(self.cfgLPPOL, 0, 1, 1, 1)
        self.cfgLMPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgLMPOL.sizePolicy().hasHeightForWidth())
        self.cfgLMPOL.setSizePolicy(sizePolicy)
        self.cfgLMPOL.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgLMPOL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgLMPOL.setObjectName("cfgLMPOL")
        self.gridlayout5.addWidget(self.cfgLMPOL, 1, 1, 1, 1)
        self.cfgHOMEPOL = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgHOMEPOL.sizePolicy().hasHeightForWidth())
        self.cfgHOMEPOL.setSizePolicy(sizePolicy)
        self.cfgHOMEPOL.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgHOMEPOL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgHOMEPOL.setObjectName("cfgHOMEPOL")
        self.gridlayout5.addWidget(self.cfgHOMEPOL, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(30, 16))
        self.label_17.setBaseSize(QtCore.QSize(40, 16))
        self.label_17.setObjectName("label_17")
        self.gridlayout5.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(30, 16))
        self.label_26.setBaseSize(QtCore.QSize(40, 16))
        self.label_26.setObjectName("label_26")
        self.gridlayout5.addWidget(self.label_26, 1, 0, 1, 1)
        self.hboxlayout7.addLayout(self.gridlayout5)
        self.vboxlayout.addLayout(self.hboxlayout7)
        self.gridlayout1.addWidget(self.frame_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(192, 68))
        self.groupBox.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox.setBaseSize(QtCore.QSize(192, 68))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridlayout6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridlayout6.setObjectName("gridlayout6")
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(85, 16))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setBaseSize(QtCore.QSize(70, 16))
        self.label_8.setObjectName("label_8")
        self.gridlayout6.addWidget(self.label_8, 0, 0, 1, 1)
        self.cfgDEFVEL = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgDEFVEL.sizePolicy().hasHeightForWidth())
        self.cfgDEFVEL.setSizePolicy(sizePolicy)
        self.cfgDEFVEL.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgDEFVEL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgDEFVEL.setBaseSize(QtCore.QSize(80, 16))
        self.cfgDEFVEL.setMaximum(999999999.0)
        self.cfgDEFVEL.setSingleStep(0.01)
        self.cfgDEFVEL.setObjectName("cfgDEFVEL")
        self.gridlayout6.addWidget(self.cfgDEFVEL, 0, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem5, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(40, 36))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_16.setBaseSize(QtCore.QSize(70, 16))
        self.label_16.setObjectName("label_16")
        self.gridlayout6.addWidget(self.label_16, 1, 0, 1, 2)
        self.cfgSTRTVEL = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgSTRTVEL.sizePolicy().hasHeightForWidth())
        self.cfgSTRTVEL.setSizePolicy(sizePolicy)
        self.cfgSTRTVEL.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgSTRTVEL.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgSTRTVEL.setBaseSize(QtCore.QSize(80, 16))
        self.cfgSTRTVEL.setMaximum(999999999.0)
        self.cfgSTRTVEL.setSingleStep(0.01)
        self.cfgSTRTVEL.setObjectName("cfgSTRTVEL")
        self.gridlayout6.addWidget(self.cfgSTRTVEL, 1, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem6, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(85, 16))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_9.setBaseSize(QtCore.QSize(70, 16))
        self.label_9.setObjectName("label_9")
        self.gridlayout6.addWidget(self.label_9, 2, 0, 1, 1)
        self.cfgDEFACCT = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgDEFACCT.sizePolicy().hasHeightForWidth())
        self.cfgDEFACCT.setSizePolicy(sizePolicy)
        self.cfgDEFACCT.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgDEFACCT.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgDEFACCT.setBaseSize(QtCore.QSize(80, 16))
        self.cfgDEFACCT.setMaximum(999999999.0)
        self.cfgDEFACCT.setSingleStep(0.01)
        self.cfgDEFACCT.setObjectName("cfgDEFACCT")
        self.gridlayout6.addWidget(self.cfgDEFACCT, 2, 1, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem7, 2, 3, 1, 1)
        self.gridlayout1.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.axis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(178, 80))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox_2.setBaseSize(QtCore.QSize(178, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setContentsMargins(5, 0, 5, 5)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.gridlayout7 = QtGui.QGridLayout()
        self.gridlayout7.setSpacing(6)
        self.gridlayout7.setObjectName("gridlayout7")
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(65, 16))
        self.label_20.setBaseSize(QtCore.QSize(100, 16))
        self.label_20.setObjectName("label_20")
        self.gridlayout7.addWidget(self.label_20, 0, 0, 1, 1)
        self.cfgTGTENC = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgTGTENC.sizePolicy().hasHeightForWidth())
        self.cfgTGTENC.setSizePolicy(sizePolicy)
        self.cfgTGTENC.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgTGTENC.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgTGTENC.setBaseSize(QtCore.QSize(80, 16))
        self.cfgTGTENC.setObjectName("cfgTGTENC")
        self.gridlayout7.addWidget(self.cfgTGTENC, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(60, 16))
        self.label_21.setBaseSize(QtCore.QSize(100, 16))
        self.label_21.setObjectName("label_21")
        self.gridlayout7.addWidget(self.label_21, 1, 0, 1, 1)
        self.cfgSHFTENC = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgSHFTENC.sizePolicy().hasHeightForWidth())
        self.cfgSHFTENC.setSizePolicy(sizePolicy)
        self.cfgSHFTENC.setMinimumSize(QtCore.QSize(80, 16))
        self.cfgSHFTENC.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cfgSHFTENC.setBaseSize(QtCore.QSize(80, 16))
        self.cfgSHFTENC.setObjectName("cfgSHFTENC")
        self.gridlayout7.addWidget(self.cfgSHFTENC, 1, 1, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout7)
        self.gridlayout8 = QtGui.QGridLayout()
        self.gridlayout8.setSpacing(6)
        self.gridlayout8.setObjectName("gridlayout8")
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(65, 16))
        self.label_22.setBaseSize(QtCore.QSize(100, 16))
        self.label_22.setObjectName("label_22")
        self.gridlayout8.addWidget(self.label_22, 0, 0, 1, 1)
        self.txtPCLOOP = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPCLOOP.sizePolicy().hasHeightForWidth())
        self.txtPCLOOP.setSizePolicy(sizePolicy)
        self.txtPCLOOP.setMinimumSize(QtCore.QSize(60, 16))
        self.txtPCLOOP.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtPCLOOP.setBaseSize(QtCore.QSize(80, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtPCLOOP.setFont(font)
        self.txtPCLOOP.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtPCLOOP.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtPCLOOP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPCLOOP.setObjectName("txtPCLOOP")
        self.gridlayout8.addWidget(self.txtPCLOOP, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(65, 16))
        self.label_23.setBaseSize(QtCore.QSize(100, 16))
        self.label_23.setObjectName("label_23")
        self.gridlayout8.addWidget(self.label_23, 1, 0, 1, 1)
        self.txtPositionControl = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPositionControl.sizePolicy().hasHeightForWidth())
        self.txtPositionControl.setSizePolicy(sizePolicy)
        self.txtPositionControl.setMinimumSize(QtCore.QSize(60, 16))
        self.txtPositionControl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtPositionControl.setBaseSize(QtCore.QSize(80, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtPositionControl.setFont(font)
        self.txtPositionControl.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtPositionControl.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtPositionControl.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPositionControl.setObjectName("txtPositionControl")
        self.gridlayout8.addWidget(self.txtPositionControl, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout8.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout8.addItem(spacerItem9, 1, 2, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout8)
        self.gridlayout1.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.gridlayout.addWidget(self.axis_frame, 0, 0, 1, 1)

        self.retranslateUi(axis)
        QtCore.QMetaObject.connectSlotsByName(axis)

    def retranslateUi(self, axis):
        axis.setWindowTitle(QtGui.QApplication.translate("axis", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.cfgACTIVE.setText(QtGui.QApplication.translate("axis", "Active axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("axis", "Protection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("axis", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.cfgNAMELOCK.setText(QtGui.QApplication.translate("axis", "Lock name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("axis", "Movement resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("axis", "steps in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("axis", "turn(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("axis", "Position source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("axis", "Default indexer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("axis", "Motor type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("axis", "Nominal current:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("axis", "Amps", None, QtGui.QApplication.UnicodeUTF8))
        self.cfgPOWERON.setText(QtGui.QApplication.translate("axis", "Restore power state at power on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("axis", "Motor direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("axis", "Switch polarity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("axis", "Limit+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("axis", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("axis", "Limit-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("axis", "Default motion values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("axis", "Velocity (steps/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("axis", "Start Velocity (steps/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("axis", "Acceleration time(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("axis", "Functional Encoders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("axis", "Target Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("axis", "Shaft Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("axis", "Closed loop:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("axis", "Position control", None, QtGui.QApplication.UnicodeUTF8))

